### ISSUE TITLE
Review Back Off strategy for webscoket reconnection

### ISSUE THREAD

**Issue by garretaserra** [hyperledger/aries-framework-javascript#1002]
## Current Problem
I am using a mobile agent so losing connection now and then is common and also for significant periods of time, not sure how this affects other type of agents.

From what I can see on the RecipientModule in the openWebScoketAndPickUp function there is a subscription to the WebSocket closing event so that a reconnection is tried in the future.

The interval is initially set at 50 ms and after that delay there is a reconnection attempt and the interval is doubled. I see no way to manually configure this interval or to change the back off strategy.

So, the intervals increase as follows (in milliseconds): 50 100 200 400 800 1600 3200 6400 12800 25600 51200 102400

I see 2 problems with this strategy: firstly, on the first second there are over 4 reconnection attempts which I would argue are too much. And the most problematic is that if the connection is lost for something typical like 20-30 seconds a reconnection will not be attempted after 25-50 seconds which is a lot.
Furthermore, there is no upper bound on the interval so after a couple of minutes there could be a timeout of 2-3 minutes which does not make sense in my opinion.

## Proposed Solution
In a best world scenario, it would be great if the interval and the back off strategy (and its parameters) would be configurable somehow. Nevertheless, adding something like a minimum and maximum for the interval value would probably suffice

For my use case a minimum of 1 second and a maximum of 10-30 seconds would be great but not sure it would adapt to other type of use cases.

**Comment by TimoGlastra** [comment]
I agree with the issue you raise here. Because most servers don't use heartbeats, the socket will be closed after a while which triggers the exponentional backoff quite often. 

We should make this timeout configurable. Starting with 0.3.0 we configure modules per module, so it bloats the global config a lot less. For now we can add it to the global agent config. 

Would you be willing to open a PR for this? Would probably be good to get some input on this from @JamesKEbert

**Comment by genaris** [comment]
Absolutely agree! This problem is one of the reasons why we've recently added methods for stopMediationPickup and initiateMessagePickup manually, so the app can subscribe to network events and control the framework accordingly. And there are several improvements and refactors to be done for 0.3.0 to make this more intuitive and useful.

I do also think that an initial interval of 50 ms is too real-timish (?) for this world and most likely it will fail at the firsts attempts. On the other side, more than 10 seconds causes more troubles than benefits thinking in user experience. As @TimoGlastra says, for the moment to improve this behaviour we could simply add a `minMediatorReconnectionInterval` and `maxMediatorReconnectionInterval` (or something like that) to agent config and use them in RecipientModule.

**Comment by garretaserra** [comment]
I can make a PR for this.
Do you think that the 50 ms interval value should also be configurable? It seems kind of arbitrary,
Should the `minMediatorReconnectionInterval` be defaulted to 0 (keep current behavior as default) or should I set it to 1 second?
Same for the `maxMediatorReconnectionInterval` should I set it to a default of 10 seconds or if not provided do not have maximum value (keep current behavior as default)?

**Comment by genaris** [comment]
> I can make a PR for this. Do you think that the 50 ms interval value should also be configurable? It seems kind of arbitrary, Should the `minMediatorReconnectionInterval` be defaulted to 0 (keep current behavior as default) or should I set it to 1 second? Same for the `maxMediatorReconnectionInterval` should I set it to a default of 10 seconds or if not provided do not have maximum value (keep current behavior as default)?

Great! Find me in Discord (GenAris#4962) if you need some help in setting up environment for AFJ. To be more aligned with terms of exponential backoff algorithms and other configs within AFJ, I would say the two parameters to set up in agent config must be:
- **baseMediatorReconnectionIntervalMs** (b): defaults to 50 (current behaviour). So attempts will be done in b, 2*b, 4*b, 8*b, etc.
- **maximumMediatorReconnectionIntervalMs**: defaults to 0 (unlimited, current behaviour). Maximum interval between attempts

So this means that if you set a `baseMediatorReconnectionIntervalMs` to 1000 and `maximumMediatorReconnectionIntervalMs` to 10000, when going offline it will retry in 1, 2, 4, 8, 10 seconds and it will keep trying each 10 seconds until it is connected.

Important: reset the interval once it successfully connects! Quickly reviewing the current codebase, I think it is not doing that and will be a problem in unstable network environments :cry:

**Comment by TimoGlastra** [comment]
Small suggestion: make the default for `maximumMediatorReconnectionIntervalMs` either `Infinity` (harder in non JavaScript config with e.g. the rest so less prefered) or `undefined`. 0 feels hacky to me as 0 is a valid maximum (do not wait).

**Comment by JamesKEbert** [comment]
Sorry for jumping in a bit late, trying to catch up on things. 

I agree that the current behavior isn't necessarily ideal, but if I recall correctly, one of the reasons we didn't do a say 10 second interval was that if the mediator is just offline or some more permanent issue, we didn't necessarily want to keep retrying for a long time. For instance, we may want to try to reconnect a maximum of 30 times or something before then requiring manual user input to try again. 

So, having a maximum attempts config might also be a decent idea to give flexibility to the end developer (and this was deemed outside the scope of the initial implementation, but I'm glad it got brought back up).

Thoughts?

**Comment by genaris** [comment]
> Sorry for jumping in a bit late, trying to catch up on things.
> 
> I agree that the current behavior isn't necessarily ideal, but if I recall correctly, one of the reasons we didn't do a say 10 second interval was that if the mediator is just offline or some more permanent issue, we didn't necessarily want to keep retrying for a long time. For instance, we may want to try to reconnect a maximum of 30 times or something before then requiring manual user input to try again.
> 
> So, having a maximum attempts config might also be a decent idea to give flexibility to the end developer (and this was deemed outside the scope of the initial implementation, but I'm glad it got brought back up).
> 
> Thoughts?

Yeah I think a maximum retry count might be useful in certain scenarios, although this should be accompanied by an event to inform the application when the framework has given up (then the app can  `initiateMessagePickup()` again anytime it wants, i.e. when user inputs or network connection is restored). These events are part of what I'm thinking for the refactor of mediation/pickup (as started in #800), hopefully for for 0.3.x (if time allows it :sweat_smile:). I'll add this retry count to the list of features to include there.

**Comment by JamesKEbert** [comment]
> although this should be accompanied by an event to inform the application when the framework has given up

Good point 👍 

> I'll add this retry count to the list of features to include there.

Awesome. Thanks for the work on this @genaris & @garretaserra (good GH issue too btw)
