### ISSUE TITLE
Mismatch of version in transaction author agreement and acceptance mechanisms response

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#1010]
If agent’s config contains `version` 0.1, then `AuthorAgreement` contains `version` 2.0 which seems correct because `text` attribute contains “Transaction Author Agreement V2“ but `AcceptanceMechanisms` contains `version` 0.1. This fails with `CommonInvalidStructure` error, respective with “Calculated hash of concatenation `version` and `text` doesn't equal to passed `hash` value.” thrown by Indy SDK function `prepare_acceptance_data` to which we pass `authorAgreement.text` and `authorAgreement.digest` gotten from ledger and `taa.version` from our agent config.

If agent’s config contains version 2.0 AFJ throws an error because of condition `authorAgreement.acceptanceMechanisms.version !== taa.version` and `AcceptanceMechanisms` containing `version` 0.1.

**Comment by TimoGlastra** [comment]
What's the difference between the acceptance mechanism version and the taa version?
