### ISSUE TITLE
Is AFJ dependent on React Native and NodeJs?

### ISSUE THREAD

**Issue by Yellowsun0003** [hyperledger/aries-framework-javascript#1026]
Are there any plans of making AFJ compatible with other frameworks apart from React Native and Node JS?  What if I have to use AFJ for an app developed with Angular framework. As per the document, it shows the React Native and Node JS as features of AFJ. So, the doubt comes now about compatibility with other features. There could be platform dependencies which are still not addressed and how that should be tackled?

**Comment by blu3beri** [comment]
Aries Framework JavaScript currently does not work in the browser. We are working in separating all the components so maybe in the near future it would be possible to have a minimal agent in the browser. 

I have not tested it myself with Angular + Ionic for mobile development and it might be interesting to look at.
