### ISSUE TITLE
Credential Offer using AFJ 2.0 doesn't contain the name of schema based on which it has been offered

### ISSUE THREAD

**Issue by Yellowsun0003** [hyperledger/aries-framework-javascript#1027]
While we were using AFJ 1.0, we could offer credentials based on the schema and that could be seen clearly while accepting the offer. So, the user knew which set of credentials have been offered. But now, in AFJ 2.0, we are getting the word "Credential" instead of schema name "xxxx_Credential" for different schema offers.

Now the "CredentialRecord" has been replaced by "CredentialExchangeRecord" in AFJ 2.0   

The "CredentialExchangeRecord" class has slightly varied set of attributes and possibly the "credential_Id" was responsible for fetching the credentailName. However, its not coming up now.

**Comment by TimoGlastra** [comment]
Hi @Yellowsun0003,

The same data is still accessible in AFJ 0.2.0, however it is only added to the credential record after the offer has been accepted. Please see the following part of the migration guide on how to achieve the same in 0.2.0: https://aries.js.org/guides/updating/versions/0.1-to-0.2#data-from-received-messages-only-stored-in-record-after-accepting

**Comment by TimoGlastra** [comment]
Closing this as there is a workaround and it is still possible in 0.2.0. Please open a new issue if you're still running into issues
