### ISSUE TITLE
macOS arm - missing symbol called

### ISSUE THREAD

**Issue by teodem** [hyperledger/aries-framework-javascript#1039]
Hello everyone 

I am having great problems running the demo on my macOS with M1 (arm). The installation of the libraries was successful. 
The problem is in the demo execution, after `yarn install` when I run `yarn alice` or `yarn faber` I get this error:

` dyld[42534]: missing symbol called
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. `

I tried looking everywhere how to solve it but nothing. Does anyone have any ideas?
Premise: I also redid the clean installation of node via nvm with rosetta2. Same result.

Thank you very much!

Node version: v18.10.0
Yarn version: 1.22.19
macOS: Monterey 12.4
Python: 3.9.7

**Comment by blu3beri** [comment]
Hi!

Where on your system is libindy located? And could you run `file` on that? And also provide the output of `file $(which node)`?

**Comment by teodem** [comment]
Hi

the location (as reported by documentation) is: /usr/local/lib/

`file` result:
`libindy.dylib: Mach-O 64-bit dynamically linked shared library arm64`
and for the other:
`/Users/M/.nvm/versions/node/v18.10.0/bin/node: Mach-O 64-bit executable x86_64`

**Comment by blu3beri** [comment]
Okay, your node version is for x86_64 and not for ARM. You have to remove your node binary and reinstall but for ARM. This will likely fix the issue (after reinstalling you also have to reinstall the node_modules).

**Comment by teodem** [comment]
hello, yes. I tried to remove and install again, following this [https://stackoverflow.com/questions/65342769/install-node-on-m1-mac](url). If i run `node -p "process.arch` i still get `x64`, i really don't get why since i've re-installed the arm dedicated node. Also, i've removed all node_modules, but i still get the same error..

**Comment by blu3beri** [comment]
Did you remove all your x86 node versions? You might have multiple. 

Running `which node` tells you where it is and `file PATH/TO/NODE` tells you the architecture. If node is arm and the libindy is arm everything should work.

**Comment by teodem** [comment]
Hi, thank you again for your support. Yes you were right, things got messed up, there was a node version installed via nvm and one via pkg, i cleaned all up and installed fresh for arm. Now, i've the proper result:

```
/usr/local/bin/node: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64
- Mach-O 64-bit executable x86_64] [arm64]
/usr/local/bin/node (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/bin/node (for architecture arm64):	Mach-O 64-bit executable arm64
```
On the other and, the libindy in not working anymore. I've removed it and cleaned up, and tried the installation again. When i do the check command i get:

```
/Users/.npm/_npx/87faa1a214dd32c6/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/Users/.npm/_npx/87faa1a214dd32c6/node_modules/indy-sdk/build/Release/indynodejs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/Users/.npm/_npx/87faa1a214dd32c6/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/.npm/_npx/87faa1a214dd32c6/node_modules/indy-sdk/src/indyBinding.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```
Thank you once again for your support

**Comment by blu3beri** [comment]
This error means removing your `node_modules` folder and running `yarn install` or `npm install`.

**Comment by teodem** [comment]
Problem solved. What i did:

- Removed all Node files, everything, in all folders and subfolder making sure that node was completely uninstalled
- Removed libindy and unistalled aries-framework/node
- Re-installed Node with brew (using arch)
- Re-installed libindy and aries-framework/node
Last but not least, a fresh restart of the Mac since yarn was not working anymore (with segmentation fault). 

Thank you very much for your tipps and time! Suggestion: i would update the documentation for Mac arm with a check of which Node is installed. I messed up, but maybe could be helpful for others :)
