### ISSUE TITLE
Update indy-sdk-react-native to 0.3.0 in 0.3.0-pre branch

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1055]
indy-sdk-react-native 0.3.0 has been release: https://github.com/hyperledger/indy-sdk-react-native/releases/tag/0.3.0.

Make sure to include a breaking change message in the PR body that mentions the updated installation instructions

**Comment by TimoGlastra** [comment]
Can you pick this up @JamesKEbert?

**Comment by JamesKEbert** [comment]
Yep, I'll do this tomorrow 👍  (would you like @KolbyRKunz to update the aries.js.org docs too?)

**Comment by TimoGlastra** [comment]
> would you like @KolbyRKunz to update the aries.js.org docs

Yes please!

**Comment by TimoGlastra** [comment]
> Yep, I'll do this tomorrow 👍

Any update on this?
