### ISSUE TITLE
Remove ProofProtocolVersion enum in 0.3.0-pre

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1056]
As they are now dynamically registered, an enum doesn't work. This is also needed to make the credentials and proofs API consistent.

**Comment by TimoGlastra** [comment]
@NB-MikeRichardson is this something you can pick up as well?

**Comment by NB-MikeRichardson** [comment]
Sure. I can do that today.

I assume we just want to replace the enum with a string?? (which I think is what we do in the credentials module)

**Comment by TimoGlastra** [comment]
For the records, yes it can be a string. For other places it sometimes should be a dynamic type (but I think you already added that in the proofs api when you updated it to align with the credentials api).

We have the `ProtocolVersionType` in the `ProofsApiOptions`

**Comment by TimoGlastra** [comment]
Also, I just noticed the `requestProof` method doesn't specify the proof services, and proof formats, which removes the type hinting. Can you add it with the PR?


In `ProofsApi.ts`:
```
public async requestProof(options: RequestProofOptions<PFs, PSs>): Promise<ProofRecord> {
```

**Comment by NB-MikeRichardson** [comment]
On it

**Comment by NB-MikeRichardson** [comment]
Looks like the same issue with `proposeProof `as well. Will fix this too.
