### ISSUE TITLE
Replace indy sdk with indy vdr

### ISSUE THREAD

**Issue by cvarjao** [hyperledger/aries-framework-javascript#1063]
Indy VDR is replacing Indy SDK, does it have all the features needed for AFJ? can/should we start moving to VDR?

**Comment by swcurran** [comment]
To be a bit more precise, Indy SDK is being replaced by all three of [Indy VDR](https://github.com/hyperledger/indy-vdr) / [Indy Shared RS](https://github.com/hyperledger/indy-shared-rs) and [Aries Askar](https://github.com/bcgov/aries-askar).

**Comment by blu3beri** [comment]
Yes @swcurran is correct. Work was done and Askar and vdr are done. However credx is not done yet (very very close). However we did not have the time yet to fix it and integrate it into AFJ. When everything is modularised it should be easier to integrate so it might still take some time for full integration of the shared components.
