### ISSUE TITLE
Remove dependency on indy ledger service from sov did resolver/registrar

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1066]
As part of making the framework more modular and less dependant on indy/indy-sdk we need to move away from the current ledger api / ledger service as they're heavily focused on indy/ the indy-sdk. 

To make the transition easier we can already start by making some internal adjustments that will prepare for the transition to generic AnonCreds / did services. this means the ledger service will be removed and replaced by the did resoler/registrar and AnonCreds interface. 

As a first start:
- Rename `SovDidResolver` to `IndySdkSovDidResolver` (or something like that)
- Rename `SovDidRegistrar` to `IndySdkSovDidRegistrar` (or something like that)
- Move the contents of the `registerPublicDid` to the `IndySdkSovDidRegistrar` and remove the dependency on the `IndyLedgerService` class in the registrar. It can still depend on the `IndyPoolService`, so maybe some things should be moved there (like TAA, signing, etc..)
- Move the contents of the `registerPublicDid` and `setEndpointsForDid` to the `IndySdkSovDidRegistrar` and remove the dependency on the `IndyLedgerService` class in the registrar. It can still depend on the `IndyPoolService`, so maybe some things should be moved there (like TAA, signing, submitReadRequest, submitWriteRequest)
- Move the contents of the `getPublicDid` and `getEndpointsForDid` to the `IndySdkSovDidResolver` and remove the dependency on the `IndyLedgerService` class in the resolver. It can still depend on the `IndyPoolService`, so maybe some things should be moved there (like TAA, signing, submitReadRequest, submitWriteRequest)
- Deprecate the `getPublicDid`, `getEndpointsForDid`, `registerPublicDid` and `setEndpointsForDid` methods in the `IndyLedgerService`
- Deprecate the `getPublicDid` and `registerPublicDid` methods in the `LedgerApi` (mark them as `@deprecated` and point towards the did resolver and registrar api (`agent.did.resolve`, `agent.dids.create`)

**Comment by sairanjit** [comment]
@TimoGlastra Can you assign me this?
