### ISSUE TITLE
Ledger API registerCredentialDefinition behaviour when ledger or wallet are reset

### ISSUE THREAD

**Issue by genaris** [hyperledger/aries-framework-javascript#1072]
While adapting AATH for 0.3.0, I've [noticed](https://github.com/hyperledger/aries-agent-test-harness/blob/6620bcb0e48c5237e848df7d4638e64436ada222/aries-backchannels/javascript/server/src/controllers/CredentialDefinitionController.ts#L58) that there is a change in Ledger API's `registerCredentialDefinition` method internal behaviour that makes a bit difficult to manage the case where either agent's wallet or ledger are reset (mostly common in development environments):

1) If we attempt to register a credential definition that exists on the ledger but not in the wallet, it will throw an error (as opposed to 0.2.x, where it just returns the credentialDefinitionId silently);
2) If we attempt to register a credential definition that exists on the wallet but not in the ledger, it will return the stored credential definition. However, no actual credential definition will be registered on the ledger

This new logic makes sense for production deployments, but I'm wondering if there is a way to allow this inconsistencies in an elegant way (in AATH I've called `IndyLedgerService` directly, but this will not store the `CredentialDefinitionRecord` in the wallet). 

A few more details (some not strictly related to this) that I don't want to forget analyzing:
- Why `registerSchema` won't throw an error when an schema is present in ledger but not in the wallet?
- [./docs/getting-started/ledger.md](https://github.com/hyperledger/aries-framework-javascript/blob/f777b3ddc287ecc73ffec2d98e14d2d84a9b8039/docs/getting-started/ledger.md) is outdated and the example is wrong: sets `didIndyNamespace` fields when it should be `indyNamespace`. 
- By the way, why there are still a few getting started documents here (ledger.md and proofs.md, which is also outdated) and not directly in aries-framework-docs repo?

**Comment by morrieinmaas** [comment]
@TimoGlastra of course
