### ISSUE TITLE
Remove Ack status type of FAIL

### ISSUE THREAD

**Issue by JamesKEbert** [hyperledger/aries-framework-javascript#1074]
According to a recent Aries RFC PR (https://github.com/hyperledger/aries-rfcs/pull/727), we should remove the status type of FAIL in Acks/AckMessage. It does not appear we are able to utilize this status anywhere in the framework.

**Comment by TimoGlastra** [comment]
@rapaktech  Remove the `AckStatus` of type `FAIL` from the `AckMessage.ts` file

**Comment by rapaktech** [comment]
On it
