### ISSUE TITLE
Do not log the wallet key (or other sensitive information) to the console

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1081]
If we do log it, it should be trace.

Places:
- wallet key
- postgres storage data (also in walletConfig)

In production we should assume people run the framework with log level info. We should make sure to never logs really private data like keys (maybe in trace in exceptional cases), and otherwise we should only log data that could contain PII in debug/trace messaegs. Info, warning, error should not contain sensitive information.

**Comment by rapaktech** [comment]
Okay. On it

**Comment by rapaktech** [comment]
@TimoGlastra I think we can close this now?
