### ISSUE TITLE
Remove PresentationExchangeRecord file

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1087]
https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/core/src/modules/proofs/repository/PresentationExchangeRecord.ts

**Comment by TimoGlastra** [comment]
@rapaktech just remove the file 😆

**Comment by rapaktech** [comment]
You got it. You haven't assigned me the issue tho 😉

**Comment by TimoGlastra** [comment]
Can't assign you until you've commented on the issue sadly 🤷

**Comment by rapaktech** [comment]
@TimoGlastra we can close this now
