### ISSUE TITLE
AutoAcceptProof.ContentApproved on latest AFJ works incorrectly

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/aries-framework-javascript#1095]
Running the `demo/` on main right now issues a credential and that all works fine. However, when requesting a proof, `Alice` automatically send a response to this proof while `autoAcceptProof` is on `AutoAcceptProof.ContentApproved` which MUST require one manual acceptance step. I will see if I can find the issue, but this should not be used in production as any agent with this setting on will automatically share any requested proof.

**Comment by TimoGlastra** [comment]
With latest AFJ do you mean 0.2.5 or 0.3.0-alpha?

**Comment by blu3beri** [comment]
> With latest AFJ do you mean 0.2.5 or 0.3.0-alpha?

It just takes AFJ from main I assume with `"@aries-framework/core": "*"` as dependency, so I assume its 0.3.0-alpha.13

**Comment by TimoGlastra** [comment]
Ok! Please let me know if you can find the issue. Seems problematic

**Comment by genaris** [comment]
I confirm this is happening on current 0.3.0-alpha. I'm using V1 protocol and doing a proof request from verifier side (no previous proposal). My understanding is that in such scenario `shouldAutoRespondToRequest` would always return false, so wouldn't do the presentation automatically.

**Comment by TimoGlastra** [comment]
@blu3beri any updates on this?

**Comment by blu3beri** [comment]
Small tl;dr here of what happened. The implementation seemed correct, but it returned a `boolean | Promise<boolean>` and it actually was just a `Promise<boolean> which we did not await. So it would check and return `false` but wrapped inside a Promise which is truthy.

We need more eslint rules to catch these things (you MUST mark async code with void / await) 👀
