### ISSUE TITLE
JSON-LD Tests should use local jsonld loader

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1097]
We don't want tests to depend on internet connectivity. The w3c credential service already depend on the local jsonld loader, but it seems the new jsonld credential format service don't.

**Comment by TimoGlastra** [comment]
@NB-MikeRichardson is this something you could pick up?

**Comment by NB-MikeRichardson** [comment]
Sure. I can do that.

**Comment by NB-MikeRichardson** [comment]
Should we just add this to the list of items in issue #1089

**Comment by NB-MikeRichardson** [comment]
Actually I think just leave this issue as it is: I'll do this one first and get a PR in for this issue only.

**Comment by NB-MikeRichardson** [comment]
If I run the w3cCredentialService tests (in modules/vc/__tests__/W3cCredentialService.test.ts) with my internet connection turned off I get the` jsonld.invalidUrl` error so I am not sure what I am trying to achieve with this issue.

**Comment by NB-MikeRichardson** [comment]
It looks like the custom loader has a call to jsonld.frame for did: URLs :-

```
    if (url.startsWith('did:')) {
      result = await jsonld.frame(result, {
        '@context': result['@context'],
        '@embed': '@never',
        id: url,
      })
    }
    
```
This code (deep inside the digital credentials library is resolving a context by going across the internet).

I tested by bypassing this code and hard-wiring the result and it works.

Not sure what is wrong with the above: I shall see if i can find out.

**Comment by NB-MikeRichardson** [comment]
There is an issue (Issue #1111 ) which documents the problem with the loader

**Comment by NB-MikeRichardson** [comment]
This issue can now be closed
