### ISSUE TITLE
Allow multiple connections for same verkey

### ISSUE THREAD

**Issue by gnarula** [hyperledger/aries-framework-javascript#110]
MessageReceiver assumes that only one connection would exist for a given recipient verkey which is not necessarily true if the agent is using a public DID.

An alternative would be to use the sender and recipient verkey together to find a connection uniquely?

**Comment by TimoGlastra** [comment]
Could you provide a use case of a situation where you would use the public DID for communication?

In most cases you would use a public DID for the invitation, and will then create a unique pairwise DID for that connection. I don't know of any use case where the public DID is used to create the connection.

As for the usage of a public DID in the invitation, see #84

**Comment by gnarula** [comment]
> In most cases you would use a public DID for the invitation, and will then create a unique pairwise DID for that connection. I don't know of any use case where the public DID is used to create the connection.

Interesting, how does one ensure that the pariwise DID that's created is indeed controlled by the same entity that controls the public DID? Are the messages signed by the verkey of the public DID along with the pairwise DID?

> As for the usage of a public DID in the invitation, see #84

Am I right to believe the answer to my question above is invitations using public DIDs always require resolution of endpoint from the ledger and never include the endpoint themselves?

**Comment by TimoGlastra** [comment]
> Interesting, how does one ensure that the pariwise DID that's created is indeed controlled by the same entity that controls the public DID? Are the messages signed by the verkey of the public DID along with the pairwise DID?

The `connection` parameter in the connection response message must be signed by the verkey of the invitation (which can be a public DID).

From the [connection protocol RFC](https://github.com/hyperledger/aries-rfcs/tree/master/features/0160-connection-protocol#2-connection-response): "The signature data must be used to verify against the invitation's recipientKeys for continuity."

Also see:
https://github.com/hyperledger/aries-framework-javascript/blob/master/src/lib/protocols/connections/ConnectionService.ts#L222-L228

> Am I right to believe the answer to my question above is invitations using public DIDs always require resolution of endpoint from the ledger and never include the endpoint themselves?

I think so? I mean theoretically you could include both in the same invitation, but that's not what it is designed to do I think.

**Comment by gnarula** [comment]
> > Interesting, how does one ensure that the pariwise DID that's created is indeed controlled by the same entity that controls the public DID? Are the messages signed by the verkey of the public DID along with the pairwise DID?
> 
> The `connection` parameter in the connection response message must be signed by the verkey of the invitation (which can be a public DID).
> 
> From the [connection protocol RFC](https://github.com/hyperledger/aries-rfcs/tree/master/features/0160-connection-protocol#2-connection-response): "The signature data must be used to verify against the invitation's recipientKeys for continuity."
> 
> Also see:
> https://github.com/hyperledger/aries-framework-javascript/blob/master/src/lib/protocols/connections/ConnectionService.ts#L222-L228

Gotcha, I think this point from the RFC and the code above resolves my doubts about an adversary "faking" to be in control of a public DID while sharing a pairwise DID in connection response. Thanks!

The use case I had required associating a connection against a public DID. Wonder if we should have a method that allows us to resolve a connection based on the other party's public DID used for invitation? I see the invitation is persisted in the ConnectionRecord so a Repository.findByQuery might do it but if it's a common enough use case it might help to have a method for it in ConnectionsModule?

**Comment by TimoGlastra** [comment]
That seems like a valid use case.

The invitation verkey is also stored as a tag so you could do the following, but this of course doesn't allow you to query by DID:

```ts
const [connection] = await this.connectionRepository.findByQuery({
  invitationKey: 'publicDidInvitationVerkey'
});
```

I am impartial for adding this method to the `ConnectionsModule`. Maybe @jakubkoci has a stronger opinion?

**Comment by gnarula** [comment]
For an example of where public DID connections might be handy, consider the scenario below:

Let's say Alice wants to connect with Bob (a well known entity). Now if Alice sends in a Connection Request to Bob with a non public DID, Bob has no way to verify that it is Alice indeed who wants to establish a connection.

A way to solve it would be by exchanging a message later that's signed by the public DID's key to prove control over a public DID but I think it's far easier to just allow creating connections using public DIDs in the first place (provided Bob knows Alice's public DID already)

**Comment by TimoGlastra** [comment]
Closing this, please open a new issue if this is still relevant
