### ISSUE TITLE
jsonld format service interfaces should take JSON credential instead of instance of W3cCredential

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1126]
It's easier to work with the API if you can just pass the JSON of a credential instead of an instance of w3c Credential.

e..g for the createOffer method `credentialFormats.jsonld.credential. But this also applies to the other methods.

With the indy api we updated everything to take interafces / plain json over class instances and it makes working with the API (And also creating the rest wrapper) a lot easier

**Comment by TimoGlastra** [comment]
@NB-MikeRichardson is this something you can pick up?

**Comment by NB-MikeRichardson** [comment]
Sure. Assign it to me.
