### ISSUE TITLE
Not using transformed credential in jsonld credential format service

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1127]
If I create a jsonld offer like this:

```
const { credentialRecord, message } = await issuer.credentials.createOffer({
    protocolVersion: "v2",
    credentialFormats: {
      jsonld: {
        credential: JsonTransformer.fromJSON(
          {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1",
            ],
            type: ["VerifiableCredential", "UniversityDegreeCredential"],
            issuer: didCreateResult.didState.did,
            issuanceDate: "2017-10-22T12:23:48Z",
            credentialSubject: {
              degree: {
                type: "BachelorDegree",
                name: "Bachelor of Science and Arts",
              },
            },
          },
          W3cCredential
        ),
        options: {
          proofType: "Ed25519Signature2018",
          proofPurpose: "assertionMethod",
        },
      },
    },
  });
```

it will actually encode the format attachment data as:

```
{
  credential: {
    context: [
      'https://www.w3.org/2018/credentials/v1',
      'https://www.w3.org/2018/credentials/examples/v1'
    ],
    type: [ 'VerifiableCredential', 'UniversityDegreeCredential' ],
    issuer: 'did:key:z6MkqxHFgc3ndvWRKHSqdiBbGGRc7aaGWestPZt184RNChgA',
    issuanceDate: '2017-10-22T12:23:48Z',
    credentialSubject: { degree: [Object] }
  },
  options: {
    proofType: 'Ed25519Signature2018',
    proofPurpose: 'assertionMethod'
  }
}
```

This should be encoded as a VC (so `@context` instead of context, etc..). This is probably because the payload isn't being transformed to JSON...

**Comment by TimoGlastra** [comment]
@NB-MikeRichardson

**Comment by NB-MikeRichardson** [comment]
This appears to work correctly now as a result of changes made for PR # 1140 
https://github.com/hyperledger/aries-framework-javascript/pull/1140

I have added check to v2.ldproof.connectionless-credentials where we call createOffer() to ensure the attachment is encoded as Json. Seems to be correct.

**Comment by TimoGlastra** [comment]
That's great. We should probably add a test for all messages where we check the format. @NB-MikeRichardson what do you think about writing the followign test for each format once and each protocol once:

1. issue credential (complete credential exchange)
2. call agent.credential.getFormatData()
3. Check that getFormatData returns the correct content for all messages

1. request proof and verify it (complete proof exchange)
2. call agent.proofs.getFormatDAta
3. Check that getFormatData returns the correct content for all messages

We can do these steps for both v1 and v2 of the protocol + jsonld  + indy

**Comment by NB-MikeRichardson** [comment]
Sure I can do that. Should we do that as a separate PR as 1140 is starting to grow a bit?

**Comment by TimoGlastra** [comment]
Yes separate PR is fine! We could do it as part of the existing tests also, so we don't have to ad more tests
