### ISSUE TITLE
Cannot process RequestCredentialMessage for the OOB attached credential-offer

### ISSUE THREAD

**Issue by conanoc** [hyperledger/aries-framework-javascript#1129]
Test scenario:
1. Faber creates an credential-offer-message and creates an oob with it.
```js
const issueCredentialConfig = {
    label: 'Faber College',
    handshake: true,
}
const { message } = await faber.credentials.createOffer({...})
const { outOfBandInvitation } = await faber.oob.createInvitation({
    ...issueCredentialConfig,
    messages: [message],
})
```
2. Alice receives the invitation.
2.1 Alice makes a connection with Faber
2.2 After the connection, Alice sends request-credential-message to Faber
3. Faber fails to process the request-credential-message because:
    - Faber tries to find credentialRecord with connection id [here](https://github.com/hyperledger/aries-framework-javascript/blob/v0.2.5/packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts#L691)
    - But, Faber created the credentialRecord without connection id [here](https://github.com/hyperledger/aries-framework-javascript/blob/v0.2.5/packages/core/src/modules/credentials/protocol/v1/V1CredentialService.ts#L403) in Step1. So, Faber cannot find the credentialRecord and throws an error.

Solution:
In `processRequest()`, find the credentialRecord without connection id like this:
```js
    const credentialRecord = await this.getByThreadAndConnectionId(requestMessage.threadId, null)
```

**Comment by TimoGlastra** [comment]
Yep seems like a bug. If we query without the connectionId we should then afterwards make sense there is no connectionId OR the connectionId matches (to prevent hijacking a credential exchange based on threadId).

Even beter would probalbly be to also look at the outOfBand record that is present in the inbound message context and see if the thread id matches one of the message in the oob invitation. 

Thanks for reporting!

**Comment by dinbtechit** [comment]
@TimoGlastra  - Curious do we have an ETA for this bug? This is preventing us from accepting OOB credentials in our bifold based wallet (NS Wallet). Or is there any workaround that we can do in the meantime? 

Thanks in advance!

**Comment by TimoGlastra** [comment]
I don't think our team will have time soon to work on this issue. 

I'm happy to give some pointers if you want to pick it up!

**Comment by dinbtechit** [comment]
@TimoGlastra  Absolutely!  We have some bandwidth to look into this. And yes, some pointers to get started would be very helpful.

Based on this comment  https://github.com/hyperledger/aries-cloudagent-python/issues/2069#issuecomment-1582480274 it appeared like the AJF was missing to include `pthid` in `~thread` but we are not sure where to go from there.

**Comment by conanoc** [comment]
Let me add some comments about this issue.
There are two related issues here. One occurs between bifold(holder) and AFJ(issuer), and another occurs between bifold(holder) and ACA-Py(issuer).
bifold<->AFJ issue could be fixed simply by finding the credentialRecord only by `thid` as I mentioned above. This fix is on the issuer side of AFJ.

bifold<->ACA-Py issue is related with `pthid` because ACA-Py lookup `pthid` to find related message records for an OOB connection. This fix should be on the holder side of AFJ.
When you search the `setThread()` function in V1ProofProtocol.ts, you can find the proof messages containing `pthid` like this: https://github.com/hyperledger/aries-framework-javascript/blob/v0.4.0/packages/anoncreds/src/protocols/proofs/v1/V1ProofProtocol.ts#L132
But, in the case of V1CredentialProtocol.ts, only `thid`s are set for credential messages like this: https://github.com/hyperledger/aries-framework-javascript/blob/v0.4.0/packages/anoncreds/src/protocols/credentials/v1/V1CredentialProtocol.ts#L330

In the Swift framework, I addressed the second issue by ensuring that the `pthid` is assigned to all messages exchanged over the OOB connection. https://github.com/hyperledger/aries-framework-swift/pull/19/files#diff-1efb4f8e3f552182ef2c41ef023e6017fdc42f81562a15e0a90157abe91b5108R51

**Comment by dinbtechit** [comment]
@conanoc  I appreciate the detailed explanation. Our issuer side utilizes ACA-PY, while the holder end utilizes AFJ (bifold). So... would it be correct to assume that the necessary adjustments need to be made only on the holder side (AFJ) in my case?

**Comment by conanoc** [comment]
@dinbtechit Yeah, that's right.

**Comment by nbAmit** [comment]
@TimoGlastra I can work on this issue, Can you please assign to me and share pointers?

**Comment by TimoGlastra** [comment]
#1558 should fix the issue
