### ISSUE TITLE
jsonld credential should be verified before storing

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1132]
This way we make sure the credential is valid before we store it. This would have prevented #1127.

Either in `JsonLdCredentialFormatService.processCredential` before we call `w3cCredentialService.storeCredential` OR we do it inside the `w3cCredentialService.storeCredential` method.

Any thoughts? Doing it in the `storeCredential` method makes sure it is not possible to store an invalid credential, but in some cases you may have already verified it so it's not needed to verify.

**Comment by TimoGlastra** [comment]
@NB-MikeRichardson as you wrote the `JsonLdCredentialFormatService` and  @karimStekelenburg as you wrote the `W3cCredentialService`, where do you think the verification should happen?

**Comment by NB-MikeRichardson** [comment]
My inclination is to put it in the JsonLdCredentialFormatService. I am currently looking at this code for purposes of #1126 and it can be done in conjunction with that.

I think I prefer to try and catch these kind of verification errors as soon as possible, which in this instance means the `JsonLdCredentialFormatService`
