### ISSUE TITLE
AriesFrameworkError: Proof record is in invalid state done. Valid states are: request-received.

### ISSUE THREAD

**Issue by oadamovskyi** [hyperledger/aries-framework-javascript#1133]
Hello
Running **./demo** and getting this error after Faber Requesting a Proof (previously Offered Credential and accepted it as Alice) and Alice make following decision `Proof request received, do you want to accept it? yes`

**Comment by TimoGlastra** [comment]
This is because of #1095! One that is fixed it should work as expected again
