### ISSUE TITLE
Querying for tags whose content is an array

### ISSUE THREAD

**Issue by genaris** [hyperledger/aries-framework-javascript#1145]
When merging #994 we set the possibility of adding multiple connection types in order to give more flexibility to the application to categorize the different connections. This is implemented by setting the "connectionType" tag as a string array.

My question is: is there a way to do an efficient query for a tag like that if it contains more than a single element? Let's say I have a connection whose `connectionType` tag is `[ 'Mediator', 'Issuer' ]` and I want to search for all connections whose connectionType tag contains the type 'Issuer'. Is it possible to do so with Indy and Askar WQL?

**Comment by TimoGlastra** [comment]
Yes! I think you can just do the following:

```
  await faberAgent.connections.findAllByQuery({
    connectionType: ['a', 'b'],
  })
```

this will translate to:

```
    {
      'connectionType:a': '1',
      'connectionType:b': '1',
      '$and': undefined,
      '$or': undefined,
      '$not': undefined
    }
```

Indy doesn't natively support array tags, but we achieve it by having the `key:value` as the tag name.

---

Had to make two slight adjustions:
1. Add `DefaultConnectionTags & CustomConnectionTags` as return type for the `getTags` in `ConnectionRecord`, I think there's something wrong with the inference of findByQuery. 
2. Had to change the type of the connectionType tag to `Array<ConnectionType | string>` as `[ConnectionType | string]` doesn't work and means an array with one entry

**Comment by genaris** [comment]
Great! Thanks for the explanation. I've added these adjustments to #1147 so we can query connection types properly.
