### ISSUE TITLE
Add auto-acceptance for issue-credential protocol

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#116]
Basically the same as #60, but for credentials.

Checklist:
- [ ] add option to enable / disable auto-accept of credentials
    - [ ] in agent config
    - [ ] to credential record
    - [ ] to credential service methods
    - [ ] to credential module methods

**Comment by TimoGlastra** [comment]
@blu3beri

**Comment by blu3beri** [comment]
Yes, will pick this up!
