### ISSUE TITLE
process methods in CredentialService don't return anything while ConnectionService methods return the connection

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#117]
For the sake of consistency, the same as with #115 

As a user of the framework I expect the API's to be consistent. The `processXXX` methods in ConnectionService all return the connection afterwards. However the `processXXX` methods in CredentialService return nothing.

This is inconsistent and I think we should pick either one.

My preference would go to returning the credential object, as we already have it. But open to either.

**Comment by jakubkoci** [comment]
That's actually a good point. My approach usually is to not add anything which I don't need to use in the protocol flow. However, the suggested change is not so significant, so we could do it I guess.
