### ISSUE TITLE
Types mismatch for `credentials` property on `Agent`

### ISSUE THREAD

**Issue by baristikir** [hyperledger/aries-framework-javascript#1187]
# Overview
After upgrading to `"@aries-framework/core": "^0.3.1"` the types on Agents `credentials` are resulting into `any`.
Looking at the migration docs from 0.2.X to 0.3.X I couldn't find any changes regarding to `credentials`.

## Reproduce
```ts
const agent = new Agent({ config, dependencies: agentDependencies })
await agent.credentials // typed as `any`
```

**Comment by TimoGlastra** [comment]
That's definitely a bug, thanks for reporting @baristikir! 

I could reproduce it locally. One workaround you can use for now is adding an empty modules key to the agent constructor, that seemed to resolve the issue. I'll dig into it more, but for now that should do the trick:

```ts
const agent = new Agent({
  dependencies: agentDependencies,
  config: {
    label: 'hello'
  },
  modules: {}
})

agent.credentials // correctly typed with {} for modules
```

**Comment by TimoGlastra** [comment]
I've created https://github.com/hyperledger/aries-framework-javascript/pull/1188 to fix the issue. We'll try to get this into a 0.3.2 release ASAP
