### ISSUE TITLE
Remove direct dependency on indy-sdk

### ISSUE THREAD

**Issue by gnarula** [hyperledger/aries-framework-javascript#12]
It's great to see a javascript implementation that can be targeted for making an Edge Agent. I've been trying to include this in a react-native project but I reckon it's not possible to use `indy-sdk` on react-native because:

1. It assumes a nodejs environment and as a result assumes the presence of modules that aren't supported in React Native
2. It ultimately calls C code which isn't directly supported by react-native (needs to be invoked through JNI/ObjectiveC)

A better alternative might be to interface the API offered by `indy-sdk` and have 2 implementations for it - one provided by `indy-sdk` itself and the other can be a react-native module that uses the Java/iOS wrappers internally.

If this feels like a welcome addition then I can volunteer to work on the Java implementation of the react-native module that adheres to the `indy-sdk` API ;) Thoughts?

**Comment by jakubkoci** [comment]
Hi. Thank you for your suggestion. I agree we shouldn't have a direct dependency on Node.js Indy-SDK wrapper. A user of the library should be able to select it based on runtime (Node.js, React Native).

First, we would need the RN wrapper as you suggested. Fortunately, I've already implemented that as part of my day job in Absa and we agreed to open-source it. It's implemented for both iOS and Android, but it's definitely not complete. I would welcome any contribution when it's open-sourced.

Then we also need to figure out how exactly to enable the switch between these dependencies. I already discussed that briefly with @jadhavajay but I think that's something we would also appreciate any help with.

I keep you updated here about the progress with RN wrapper and then we can discuss the next steps.

**Comment by gnarula** [comment]
> Then we also need to figure out how exactly to enable the switch between these dependencies. I already discussed that briefly with @jadhavajay but I think that's something we would also appreciate any help with.

How about having an interface say `Indy` that defines all the methods that libindy exposes. The end user can decide the custom implementation at runtime. I'd imagine all classe that depend on it to require an instance of it passed down in the constructor:

```js
class IndyWallet implements Wallet {
  // .. instance members
  constructor(walletConfig: WalletConfig, walletCredentials: WalletCredentials, indy: Indy) {
    this.walletConfig = walletConfig;
    this.walletCredentials = walletCredentials;
    this.indy = indy;
  }
  // ...
}
```

If we do plan to go this way then it might be a good idea to adopt a dependency injection framework as well. At the moment everything is tightly coupled inside the `Agent` class. What do you think?

**Comment by jadhavajay** [comment]
Thanks @gnarula for the suggestions and the PR as well. Let's discuss this and other approaches (e.g. Aries VDRI) in the community call on Friday.

**Comment by jakubkoci** [comment]
I guess we don't have this dependency anymore. It was basically removed by #26. There are still `indy-sdk` dev dependency because of e2e tests and `indy-sdk` types (regarding types see #38).
