### ISSUE TITLE
Update the message type URIs from the old did:sov format to https format

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#121]
We should update the message types according to this [commit](https://github.com/hyperledger/aries-rfcs/commit/6509b84abaf5760a8ba1744c8078d513f28456db) in Aries RFCS.

I would like also to raise the question here on how to version the messages in the future. I haven't thought about that yet, so I don't have any opinion right now.

Specs:
* [Aries RFC 0348: Transition Message Type to HTTPs](https://github.com/hyperledger/aries-rfcs/blob/master/features/0348-transition-msg-type-to-https/README.md)

**Comment by TimoGlastra** [comment]
Discussed on WG Group call: We don't have a version released yet so we'll wait until the transition is complete and update in once. This way we don't have to support two types of message URI prefixes for all messages
