### ISSUE TITLE
Support legacy did sov prefix for old protocols

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1230]
This way we can start using https for newer protocols, but keep did:sov for old protocols as e.g. the trinsic wallet still doesn't support the https prefix...

**Comment by swcurran** [comment]
Is the Trinsic wallet going to continue to evolve?  @tmarkovski Or is it time to not use it as a measure for compatibility?

**Comment by TimoGlastra** [comment]
Whether we want to or not, people will use it as a measure of compatibility. So for now we don't intend to break backwards interop. 

Sadly the strategy we've implemented with all new or all old doesn't work. We need to b e 'smarter' about it.
