### ISSUE TITLE
Node-Gyp & Bindings Error

### ISSUE THREAD

**Issue by miahdouble07** [hyperledger/aries-framework-javascript#1231]
Mac M1...I've gotten the same error 2 days straight with no luck. Ive done uninstalls, reinstalls, added dependencies, etc but still get the same node-gyp error on "yarn install" and the error below on "yarn alice". 

Please help. Two others in the discord are having the same issue with no luck. See below.

/aries-framework-javascript/node_modules/bindings/bindings.js:126
  err = new Error(
        ^
Error: Could not locate the bindings file. Tried:
 → .../aries-framework-javascript/node_modules/indy-sdk/build/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/build/Debug/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/build/Release/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/out/Debug/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/Debug/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/out/Release/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/Release/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/build/default/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/compiled/18.13.0/darwin/arm64/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/addon-build/release/install-root/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/addon-build/debug/install-root/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/addon-build/default/install-root/indynodejs.node
 → .../aries-framework-javascript/node_modules/indy-sdk/lib/binding/node-v108-darwin-arm64/indynodejs.node
    at bindings (.../aries-framework-javascript/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (.../aries-framework-javascript/node_modules/indy-sdk/src/indyBinding.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] (.../aries-framework-javascript/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (.../aries-framework-javascript/node_modules/indy-sdk/src/index.js:1:14) {
  tries: [
    '.../aries-framework-javascript/node_modules/indy-sdk/build/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/build/Debug/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/build/Release/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/out/Debug/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/Debug/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/out/Release/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/Release/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/build/default/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/compiled/18.13.0/darwin/arm64/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/addon-build/release/install-root/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/addon-build/debug/install-root/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/addon-build/default/install-root/indynodejs.node',
    '.../aries-framework-javascript/node_modules/indy-sdk/lib/binding/node-v108-darwin-arm64/indynodejs.node'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by TimoGlastra** [comment]
Which version of node are you using? Did you follow the getting stated guide?

https://aries.js.org/guides/getting-started/installation/nodejs/apple-arm

**Comment by miahdouble07** [comment]
Yes I keep following it exactly. I have node v18.13.0 in vscode but Node.js v19.4.0 in Mac terminal. Idk if thats causing issues. when i run "npx -p @aries-framework/node is-indy-installed" in terminal it says libindy is installed correctly. when i run it in Mac terminal it shows errors of "using 108, requires 111"....

**Comment by TimoGlastra** [comment]
When you switch node versions you need to reinstall the indy-sdk so it will rebuild the node addon that is bundled with the package. So whenever you switch, you need to run yarn/npm install again

**Comment by TimoGlastra** [comment]
Ah that's a nasty one! :(
