### ISSUE TITLE
Registration of Wallet and Storage classes other than Indy in Agent constructor

### ISSUE THREAD

**Issue by genaris** [hyperledger/aries-framework-javascript#1235]
Currently, `Agent` class provides a way of registering `Wallet` and `StorageService` instances not based on Indy: this can be achieved by creating a `DependencyManager` before Agent constructor and register there the one we want. Something like:

```ts
    const dependencyManager = new DependencyManager()
    dependencyManager.registerContextScoped(InjectionSymbols.Wallet, IndySdkWallet)
    dependencyManager.registerSingleton(InjectionSymbols.StorageService, IndySdkStorageService)
    senderAgent = new Agent(
      {
        ...
        modules: { indySdk: new IndySdkModule({ indySdk: agentDependencies.indy }) },
      },
      dependencyManager
    )
```

As it can be seen, this is not very evident, so now we are working on extracting IndyWallet class from the core and make use of extension modules like @aries-framework/indy-sdk and @aries-framework/askar, we can simplify this procedure. For instance, we can leave the extension module to register the instances it needs and throw an error if another module has already done so.

**Comment by karimStekelenburg** [comment]
I'm not too familiar with Askar, so forgive me for asking mildly uninformed questions...

How pluggable is the database backend from the perspective of AFJ? Looking at #1211 I can see that this works with both SQLite and Postgres, nice! But let's say I'd like to use MySQL or maybe even a NoSQL backend. Would that be possible without touching the Rust layer (e.g. providing some FFI callbacks)?

**Comment by genaris** [comment]
> I'm not too familiar with Askar, so forgive me for asking mildly uninformed questions...
> 
> How pluggable is the database backend from the perspective of AFJ? Looking at #1211 I can see that this works with both SQLite and Postgres, nice! But let's say I'd like to use MySQL or maybe even a NoSQL backend. Would that be possible without touching the Rust layer (e.g. providing some FFI callbacks)?

My understanding is that currently Askar supports those two 'fixed' backends. I'm not completely sure but AFAIK there is not yet a plug-in interface to register external backends. But I do think that it would be very interesting to be able to plug a custom backend by using FFI callbacks (something like the one for the custom logger). Not sure how good it might be in terms of performance but it will be interesting to see it working.

Surely @andrewwhitehead and @blu3beri can give us good ideas about this possibility (and how feasible) it is.

**Comment by blu3beri** [comment]
Yes I believe Ariel is correct that they are fixed. However I doubt it would ever be possible with some FFI callbacks for the storing and such. I think if we really need that, Askar Storage and Askar Crypto have to become separate modules. Afterwards we can use Askar Crypto for the secure part of the secure storage and implement askar storage in pure js for the storage part of secure storage. Does that make sense?

**Comment by TimoGlastra** [comment]
I think this is done, If I misunderstood please reopen @genaris
