### ISSUE TITLE
Create IndyVdrAnonCredsRegistry without revocation

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1239]
Create an `IndyVdrAnonCredsRegistry` that implements the `AnonCredsRegistry` interface from the `@aries-framework/anoncreds` package using the indy vdr library.

- Implement the `AnonCredsRegistry` interface methods from the anoncreds package.
  - read/write schema
  - read/write credential definition
  - return not implemented error for revocation status list and revocation registry definition 
  - add tests
  - should be added to the `@aries-framework/indy-vdr` package
- Utils present in the indy-sdk package that are needed, can be copied to the indy-vdr package.
- The overall structure can stay the same (responses etc..), but we should update it to use the IndyVdrPoolService
- The `indyVdrPoolService` can be injected using `agentContext.dependencyManager.resolve(IndyVdrPoolService)`

Resources
- Specification: https://hyperledger.github.io/anoncreds-spec/
- https://hyperledger.github.io/indy-did-method/#other-indy-ledger-object-identifiers
- https://www.hyperledger.org/blog/2022/11/15/announcing-hyperledger-anoncreds-open-source-open-specification-privacy-preserving-verifiable-credentials

Can use the `IndySdkAnonCredsRegistry` as an example, but must be updated to use the `IndyVdrPoolService` and `IndyVdrPool`.

We may need to transform the structure of some objects. As the AnonCreds interfaces are different than what is stored on the indy ledger. However, the same transformations are present in the `IndySdkAnonCredsRegistry` class, so should make sure it is correct, but we can mostly copy the transformations from the existing implementaiton.

**Comment by Vickysomtee** [comment]
Working on this!
