### ISSUE TITLE
remove agent.injectionContainer property

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1242]
Was marked as deprecated in #1241, but should be removed before making the 0.4.0 release

**Comment by karimStekelenburg** [comment]
In the `BaseAgent` class there is a `injectionContaner` getter property that should be removed.

**Comment by genaris** [comment]
@2mau I've seen you've commited a fix for this in your local fork. Are you willing to submit a PR for this?

You just need to make sure all your commits are signed-off so we can merge it in.
