### ISSUE TITLE
Implement revocation methods in indy vdr anoncreds registry in AFJ

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1273]
Continuation on #1270 that implements methods to resolve and register schemas and credential definitions. But we still need to be able to resolve revocation registry definitions and revocation status lists to be able to prove and verify revocable anoncreds credentials

Same as with #1270, most of the implmeentation can be copied form the IndySdkAnonCredsRegistry, but we need to update it work with Indy VDR.

**Comment by Vickysomtee** [comment]
I'll pick this up

**Comment by genaris** [comment]
This is solved by #1328, right?

**Comment by Vickysomtee** [comment]
@genaris Yes!
