### ISSUE TITLE
Incorrect thid in response message

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/aries-framework-javascript#1309]
When responding to a DIDComm message with both an `@id` and a `~thread.thid`, it appears that AFJ will use the `@id` as the `thid` of the response message. I believe it should prefer the `thid` that was provided.

**Comment by TimoGlastra** [comment]
Is there any specific protocol where you encountered this issue?

**Comment by swcurran** [comment]
Pretty sure that is a MUST.  :-)

**Comment by TimoGlastra** [comment]
Only issue I could find is with the generic problem report message. We take the `@id` of the message that produced the processing error as the `thid`, but after reading the protocol again it must be set as the `pthid`, where the problemReport is a new thread.

**Comment by TimoGlastra** [comment]
@swcurran now that I read this: 

> ~thread: A thread decorator that places the problem-report into a thread context. If the problem was triggered in the processing of a message, then the triggering message is the head of a new thread of which the problem report is the second member (~thread.sender_order = 0). In such cases, the ~thread.pthid (parent thread id) here would be the @id of the triggering message. If the problem-report is unrelated to a message, the thread decorator is mostly redundant, as ~thread.thid must equal @id.

Shouldn't the sentence ` In such cases, the ~thread.pthid (parent thread id) here would be the @id of the triggering message. ` be the `~thread.thid` and the trigger message `thid` should be the `pthid`?

**Comment by andrewwhitehead** [comment]
I believe I encountered this with a CredentialRequest in the issue-credential 1.0 protocol.

**Comment by TimoGlastra** [comment]
Wasn't able to find anything in the credentials protocol. If you encounter it again, please let me know!

**Comment by genaris** [comment]
Some time ago I raised #588 , which seems related to this. But @TimoGlastra had some good points there. At least at that time it made sense to me that for that case the thid would be the id of offer-credential message, while offer-credential message thid would become pthid of further messages.

**Comment by TimoGlastra** [comment]
Found the issue!
