### ISSUE TITLE
Missing prover_did when accepting a Legacy Indy Credential Offer 

### ISSUE THREAD

**Issue by genaris** [hyperledger/aries-framework-javascript#1341]
After taking a look at yersterday AATH results, we could see that AFJ 0.4.0.alpha is working fine in all cases except when it acts a holder: 

Runset | ACME(Issuer) | Bob(Holder) | Faber(Verifier) | Mallory(Holder) | Scope | Results
-- | -- | -- | -- | -- | -- | --
acapy-afj | acapy-main0.8.0-rc0 | javascript0.4.0-alpha.44 | acapy-main0.8.0-rc0 | acapy-main0.8.0-rc0 | AIP 1.0 | 12 / 39 30%
acapy-dotnet-javascript | acapy-main0.8.0-rc0 | javascript0.4.0-alpha.44 | dotnet | acapy-main0.8.0-rc0 | AIP 1.0 | 2 / 12 16%
afj-acapy | javascript0.4.0-alpha.44 | acapy-main0.8.0-rc0 | javascript0.4.0-alpha.44 | javascript0.4.0-alpha.44 | AIP 1.0 | 27 / 28 96%
afj-dotnet | javascript0.4.0-alpha.44 | dotnet | javascript0.4.0-alpha.44 | javascript0.4.0-alpha.44 | AIP 1.0 | 12 / 12 100%
afj-findy | javascript0.4.0-alpha.44 | findy0.30.56 | javascript0.4.0-alpha.44 | javascript0.4.0-alpha.44 | AIP 1.0 | 17 / 17 100%
afj | javascript0.4.0-alpha.44 | javascript0.4.0-alpha.44 | javascript0.4.0-alpha.44 | javascript0.4.0-alpha.44 | AIP 1.0 | 28 / 28 100%
ariesvcx-javascript | aries-vcx1.0.0 | javascript0.4.0-alpha.44 | aries-vcx1.0.0 | aries-vcx1.0.0 | AIP 1.0 | 4 / 20 20%
dotnet-javascript | dotnet | javascript0.4.0-alpha.44 | dotnet | dotnet | AIP 1.0 | 2 / 1216%
findy-javascript-dotnet | findy0.30.56 | javascript0.4.0-alpha.44 | dotnet | findy0.30.56 | AIP 1.0 | 2 / 17 11%

When running it locally against an ACA-Py, I figured out that the issue has to do with the fact that AFJ is not including any `prover_did` in the Credential Request, which is a required field for Legacy Indy.

`IndySdkHolderService` is currently generating a random string, mostly motivated because indySdk requires it. But for the general use I think we have to also do this trick in `LegacyIndyCredentialFormatService`, just after calling holderService.createCredentialRequest, in case it does not add any `prover_did` to the request (which is the case of `AnonCredsRsHolderService`).

**Comment by TimoGlastra** [comment]
Good find!
