### ISSUE TITLE
Multi-tenant agent uses SQLite wallets for tenants even if base wallet uses postgres

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1353]
This results in loss of data

**Comment by TimoGlastra** [comment]
We store the wallet config here: https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/tenants/src/services/TenantRecordService.ts#L24

However, we shouldn't store the postgres access details when storing the wallet config. Rather we should make sure to not override the whole wallet config here: https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/tenants/src/context/TenantSessionCoordinator.ts#L183, but only the relevant pieces

**Comment by TimoGlastra** [comment]
@2mau if you can reply to this issue, I can assign you (limitation of gihtub)

**Comment by 2mau** [comment]
Reply
