### ISSUE TITLE
ProofExchangeRecord does not contain information about request and received proof

### ISSUE THREAD

**Issue by Artemkaaas** [hyperledger/aries-framework-javascript#1357]
It appears that  `ProofExchangeRecord` record does not contain any data about the sent proof request payload and proof received from the Prover.
As Verifier  I would like to show the content of the received proof on the UI (requested attributes / filled predicates), but it appears that `ProofExchangeRecord` record does not contain either the proof request payload which was sent or proof received from the Prover. It only contains the flag indicating the validity.
Also, I would like to have a history of requests/proofs. 
What is the motivation for excluding this data from the record? Can we add this information?  Or I am looking at the wrong place?

**Comment by TimoGlastra** [comment]
It has been extracted into separate DidCommMessageRecords to make it easier to support multiple protocol versions without the message classes clashing.

You can call agent.proofs.getFormatData to retrieve the data you're looking for

**Comment by Artemkaaas** [comment]
Thank you for the clarification!
