### ISSUE TITLE
Connectionless Proof Requests

### ISSUE THREAD

**Issue by Artemkaaas** [hyperledger/aries-framework-javascript#1358]
What is the proper way to create a connectionless Proof Request? 
I found that it can be done using a combination of `createRequest` and `createLegacyConnectionlessInvitation` functions, but I wonder to know if it is still recommended way? 
Does AFJ support the case when out-of-band invitation includes a proof request in the attachment? This approach seems more flexible.

**Comment by TimoGlastra** [comment]
We do support connectionless proof requests using oob. For creating you can call create request and then createInvitation on the oob module, pass the request message and set handshake to false.

There is a bug currently that prevents this from working. Hope to fix it for the 0.4.0 release. See #1250

Receiving can be done using the reveiveInvitation(Url) om the oob module as well. Attached messages will be received by the agent and you can listen for events to handle them. So e.g. ProofStateChanged will be emitted when you receive an oob invitation with a proof request attached

**Comment by TimoGlastra** [comment]
Closing. Please open a new issue if you have other questions or issues
