### ISSUE TITLE
Forward Port of Mediator to public endpoint (ngrok, localhost.run)

### ISSUE THREAD

**Issue by proteche** [hyperledger/aries-framework-javascript#138]
how to forward port to public to work with `/invitation` endpoint, & to work with react-native.

**Comment by TimoGlastra** [comment]
Good suggestion. See #139 . After this PR is merged you can run the following command to start mediators with ngrok tunneling:

```sh
docker-compose -f docker/docker-compose-mediators.yml -f docker/docker-compose-mediators-ngrok.yml up -d
```
