### ISSUE TITLE
Export types that should be publicly accessible

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#141]
Currently when using aries-framework-javascript you frequently encounter that you need to use a type that is not exported. We should define which types to export.

- protocol messages and their inner classes
- storage records
- services
- ...?

Types not exported now, but should be:
- `SchemaTemplate` from `LedgerService`

**Comment by karimStekelenburg** [comment]
I noticed when implementing a callback for the connection event listener (`agent.connections.events().on(ConnectionEventType.StateChanged, (event: ConnectionStateChangedEvent) => {....})` that the `ConnectionStateChangedEvent` is not exposed by the API.

Might be a nice addition to the (future) PR related to this issue

**Comment by TimoGlastra** [comment]
Fixed for now by exporting everything. We can create a new issue to see how to only export classes that should be public
