### ISSUE TITLE
CLI demo broken, espeically when running multiple times

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1430]
Reported by multiple people

**Comment by djleonskennedy** [comment]
During send creds

<img width="1649" alt="image" src="https://user-images.githubusercontent.com/8366455/232098038-8e8e98f6-3a33-42a6-8d67-43c0ab416e0e.png">

**Comment by genaris** [comment]
Nowadays it is running consistently fine for me [using patched ref-napi](https://github.com/hyperledger/aries-framework-javascript/issues/1452#issuecomment-1622661873)). Should we consider this fixed?
