### ISSUE TITLE
Alice agent Timeout too soon

### ISSUE THREAD

**Issue by ksanjaykumar1** [hyperledger/aries-framework-javascript#1452]
I am running the demo code. Alice's agent is resulting in a timeout while establishing a connection with Faber's agent.  
The timeout occurs when Alice's agent shares its DIDDoc and waits for Faber to share its DIDDoc for Alice. 

How can I increase the timeout period for Alice's agent? 

![image](https://github.com/hyperledger/aries-framework-javascript/assets/72605368/61299db5-8ba3-4f17-ab6b-e11f4800af0f)

**Comment by TimoGlastra** [comment]
I think increasing the timeout makes sense (maybe even remove it and add "Press escape to return"). What was the issue you encounetered when increasing the timeout?

**Comment by laygir** [comment]
Hey @TimoGlastra thank you for your quick response!

Sharing a screen recording of what I am seeing. I am pretty new on the hyperledger/aries topics, so I might be missing something very obvious.. And just to be clear, I am only running Alice and Faber, there is nothing else running on the background like a mediator.. I am not even sure if a mediator for this demo is necessary or not.

https://github.com/hyperledger/aries-framework-javascript/assets/772730/389f36bf-0cc9-465a-a8c8-d992a23e414d



fwiw:
I also tried https://github.com/hyperledger/aries-mediator-service/tree/main 
Stack came online, I see the big qr code, and the invite url
Then I only ran Alice and pasted the invite url from mediator to Alice. That ended up with an error as below;

```
2023-06-01 13:34:25,325 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://localhost:9000/; Error: (<class 'aiohttp.client_exceptions.ClientConnectorError'>, ClientConnectorError(ConnectionKey(host='localhost', port=9000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 9000)")), <traceback object at 0x40486c1440>); Re-queue failed message ...
aries-mediator-service-mediator-1  | 2023-06-01 13:34:35,361 aries_cloudagent.transport.outbound.manager ERROR >>> Outbound message failed to deliver, NOT Re-queued.
```

Cheers!

**Comment by laygir** [comment]
Here is the recording with debug logger.

https://github.com/hyperledger/aries-framework-javascript/assets/772730/a8cd7f4f-0152-4679-ba1e-c1b3240d1c42

**Comment by laygir** [comment]
Hey @TimoGlastra just wanted to gently nudge this topic in case you have a pointer for me 🙏

**Comment by genaris** [comment]
I noticed that now we are using askar, anoncreds-rs and indy-vdr for the demo. This makes me think that this can be related to `ref-napi` low performance issue we found some time ago.

The quick solution for it would be to add the patched ref-napi to `package.json`'s `resolutions` field, i.e. resulting something like: 

```json
  "resolutions": {
    "@types/node": "^16.11.7",
    "ref-napi": "npm:@2060.io/ref-napi"
  },
```

Then run `yarn install` again and should work fine.

**Note**: for this to work properly you need to be running node 18 or newer. More info about this issue in [Aries JS Docs](https://aries.js.org/guides/0.4/getting-started/set-up/aries-askar#supported-nodejs-versions-for-aries-askar)

**Comment by outSH** [comment]
Having similar error on Fedora:

```
  _____           _                   
 |  ___|   __ _  | |__     ___   _ __ 
 | |_     / _` | | '_ \   / _ \ | '__|
 |  _|   | (_| | | |_) | |  __/ | |   
 |_|      \__,_| |_.__/   \___| |_|   
                                      
error Command failed with signal "SIGINT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Checked on:
- Node v18.18.2 / NPM 10.2.1 / yarn 1.22.19, both `main` branch and resolution fix proposed by @genaris 
- Node v16.14.2 / NPM 8.10.0 / yarn 1.22.17 (only `main` branch)

OS

```
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Comment by outSH** [comment]
Having same error on ubuntu (VM):

![image](https://github.com/hyperledger/aries-framework-javascript/assets/9387513/5b8c3f80-a0ae-4661-9bbc-8071a2c6d0ad)

- I've enabled debug logs, added resolutions workaround and increased timeout in Faber `waitForConnection` to 3 minutes. Now Alice is failing (timout in rxjs). See the logs attached.
- It seems to be overall performance issue, there were 1-2 second breaks between each message, and all CPU were under heavy load (during the whole process):

![image](https://github.com/hyperledger/aries-framework-javascript/assets/9387513/035f3cb9-efda-4500-96ca-acaafe73db94)

[faber.txt](https://github.com/hyperledger/aries-framework-javascript/files/13208403/faber.txt)
[alice.txt](https://github.com/hyperledger/aries-framework-javascript/files/13208407/alice.txt)

- **I've replaced Agent modules (https://github.com/hyperledger/aries-framework-javascript/blob/main/demo/src/BaseAgent.ts#L97) with `getLegacyIndySdkModules()` (had to cast it to any in order to compile) and connection runs smoothly now, with tiny CPU usage.**

### My setup

``` sh
vagrant@CactusDevVM:~$ node -v
v18.18.2
[alice.txt](https://github.com/hyperledger/aries-framework-javascript/files/13208402/alice.txt)
[faber.txt](https://github.com/hyperledger/aries-framework-javascript/files/13208404/faber.txt)

vagrant@CactusDevVM:~$ npm -v
9.8.1
vagrant@CactusDevVM:~$ yarn -v
1.22.19
vagrant@CactusDevVM:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by genaris** [comment]
@outSH Today we've merged an update that uses patched `ref-napi` and `ffi-napi`. There is still some work to do to remove indy-sdk dependency from this repo but the demo should be easier to set-up.

Could you pull these new changes and check again? Make sure to clean-up your repo (e.g. remove `node_modules`) so everything is in place.

**Comment by outSH** [comment]
@genaris Yes, everything is working fine now (on node v20.9.0), thank you!

Any ETA when these updates be available in a package? A week / month from now?

**Comment by genaris** [comment]
> @genaris Yes, everything is working fine now (on node v20.9.0), thank you!
> 
> Any ETA when these updates be available in a package? A week / month from now?

Hard to say how much time will take to get 0.5.0 released, but you can already use an alpha package (you just need to use alpha channel, e.g. `yarn add @aries-framework/core@alpha`) to get latest unstable AFJ version, matching the `main` branch state.

I'm closing this issue given that apparently now we fixed the timeout problem.
