### ISSUE TITLE
How Aries is working?

### ISSUE THREAD

**Issue by HeeGyoung** [hyperledger/aries-framework-javascript#1457]
Hi, I've been studying self-sovereign identity recently.
After reading and trying to do this tutorial (https://aries.js.org/guides/tutorials/issue-a-credential),
I'm confused below:
1. After initializing the agent, which indy network is Aries heading? dev? test? Is it possible to connect to von-network on my local?
2. Connection tutorial (https://aries.js.org/guides/tutorials/create-a-connection) was working. But, the Credential tutorial doesn't work.
<img width="1425" alt="Screen Shot 2023-05-12 at 5 53 12 PM" src="https://github.com/hyperledger/aries-framework-javascript/assets/89409087/59c22e01-25bf-4026-a365-29d09ffe635b">
How could I solve this error?

**Comment by HeeGyoung** [comment]
I solve this issue. 
The reason was that when I started von-network locally, It uses "host.docker.internal" as the IP address but Aries call this API outside of the network.
So, I add `127.0.0.1 host.docker.internal` in my host file (at the end of the host file) and it worked !

**Comment by bilal12367** [comment]
> I solve this issue. The reason of PoolLedgerTimeout was that when I started von-network locally, It uses "host.docker.internal" as the IP address but Aries call this API outside of the network. So, I add `127.0.0.1 host.docker.internal` in my host file (at the end of the host file) and it worked !

Hi heegyoung, I am facing this exact issue. It says PoolLedgerTimeout. can you explain it in detail what have you done to resolve this issue??

**Comment by HeeGyoung** [comment]
@bilal12367 Hello, my case was like below.

If you did not change anything about von-network settings, you could access here after building up the network .
<img width="884" alt="Screenshot 2023-07-14 at 5 21 36 PM" src="https://github.com/hyperledger/aries-framework-javascript/assets/89409087/31d73081-3aff-4620-a518-05d7118af737">

As you can see, von-network uses "host.docker.internal" as the domain(or IP) to call the von-network nodes.
Inside of the docker or among docker containers in the same docker network, It does not matter because docker made "host.docker.internal" to support the internal IP of the containers. However, my problem comes when Aries tries to find the IP information of the von-network. 

When Aries, inside of my application, tries to find the IP information of the von-network to make a connection with it, the domain "host.docker.internal" was returned and used it.  So, When Aries tried to call "http://host.docker.internal:port" outside of the von-network that is working in the docker,  Aries can not reach the von-network.
So, I have to add the domain information into my host file like below.
<img width="523" alt="Screenshot 2023-07-14 at 5 36 46 PM" src="https://github.com/hyperledger/aries-framework-javascript/assets/89409087/e1328e9f-58df-4114-a1bd-6260c3f84802">

And then, It worked.
