### ISSUE TITLE
Need help on backup and restore functionality

### ISSUE THREAD

**Issue by Sshovon** [hyperledger/aries-framework-javascript#1464]
I am working on a project requiring backing up and restoring the wallet with all its previous connections and credentials. Are there any workable functionalities to implement backup and restore in Aries Bifold wallet?

**Comment by TimoGlastra** [comment]
There are two methods available: import and export, which you can use to make an export/import of your wallet.

```
agent.wallet.export
```

Is this what you're looking for?

**Comment by Sshovon** [comment]
Yes, I am looking for this one. I found export import method in /packages/core/src/wallet/Wallet.ts . Are you talking about these methods? If not, could you let me know which file these two methods are written in? It would be much helpful.

**Comment by TimoGlastra** [comment]
It's in the `IndySdkWallet` or `AskarWallet` (dependant on which wallet you use). 

However, you can access it from the wallet api directly (using `agent.wallet.export`):

https://github.com/hyperledger/aries-framework-javascript/blob/11366e540421517ce21e8cca8781741fc482be8e/packages/core/src/wallet/WalletApi.ts#L112-L118

**Comment by Sshovon** [comment]
I have worked on import and export modules. After export a new file is generated which is used to import the wallet. The import functions also works. But the problem arises after importing, new wallet doesn't set automatically. Even walletConfig.id doesn't change. 
For import, I have delete the wallet using agent.wallet.delete() and called agent.wallet.import() afterward. I have also tried to initialize the wallet  after import using agent.wallet.initialize(). Still didn't worked.
Can you help me this regard? 

![image](https://github.com/hyperledger/aries-framework-javascript/assets/47460398/0fd33ad1-5c07-4eba-8528-da84a0ab6ca8)

**Comment by TimoGlastra** [comment]
What wallet are you using? AskarWallet or IndySdkWallet?

> For import, I have delete the wallet using agent.wallet.delete() and called agent.wallet.import() afterward

I think this is to prevent from overwriting a local wallet

> Still didn't worked.

What do you mean exactly with still doesn't work? Are you getting an error?

**Comment by Sshovon** [comment]
I am using IndySdkWallet. 
For import, I am deleting the current wallet and creating a new wallet.  After import I am getting no error. The import functionality creates sqlite.db,sqlite.db-shm,sqlite.db-wal files in mobile storage. I am attaching a screenshot of after and before importing wallet. But the problem is after import the wallet doesn't load credentials or connections from the export file. And also it loses the pin related information of the wallet as I deleted the wallet. So I can't login using the same pin. It gives incorrect pin in the app though the salt remains same. 
In short,
* I have deleted wallet and import it afterward.
* After import, wallet isn't functioning as expected.
**Am I following the correct sequence for importing?**
One notable point is,
An empty wallet export file is around 8kb. And if i add some connection credentials, then the size increases. Now if I import in a empty wallet  a file size of  50kb (includes some connection, credentials),in the app nothing shows after import. But if I export again, I get a export file size of 50kb, though the wallet shows empty. Logically the new export file should be 8kb as the wallet is empty.  I think the import function is working, but it doesn't have any effect on the app.
![image](https://github.com/hyperledger/aries-framework-javascript/assets/47460398/6e754c09-70ad-4471-af05-627e363a61a6)

**Comment by Sshovon** [comment]
I have bypassed the pin authentication mechanism to enter the wallet. And the import function worked. Yet need some testing to check every functionality of the wallet. After deleting the previous wallet and importing a new one, the pin mechanism fails to verify the pin and always shows an incorrect pin alert.
