### ISSUE TITLE
Unable to fetch tails registry if the schema name contains spaces

### ISSUE THREAD

**Issue by jleach** [hyperledger/aries-framework-javascript#1478]
When fetching the tails URL is the schema name has spaces in it iOS (not confirmed on Android) will fails because the URL is not recognized:

```console
Card:CL_ACCUM:41e28904-4584-4250-a274-3723f628256b
 ERROR  ERROR: Error while retrieving tails file from URL https://tails-test.vonx.io/2K2h7kf8VGTLtfoxJgWazf:4:2K2h7kf8VGTLtfoxJgWazf:3:CL:814555:Member Card:CL_ACCUM:41e28904-4584-4250-a274-3723f628256b {
....
    "code": "ENSURLERRORDOMAIN-1002",
    "message": "unsupported URL",
    "domain": "NSURLErrorDomain",
```

I think we should add `encodeURI()` just before line 69 [here](https://github.com/hyperledger/aries-framework-javascript/blob/efc0ddfd23290f99bfde6a3e27c4f1e682630b2e/packages/react-native/src/ReactNativeFileSystem.ts#L65). It can be added earlier in the calls stack to effect all other platforms but since nobody else is complaining it may be on RN only.

**Comment by TimoGlastra** [comment]
Interesting. In general spaces aren't allowed in urls, so this should probably be fixed at the issuer side.

I'm fine with adding this change, as it can't hurt

**Comment by jleach** [comment]
@TimoGlastra Noted. Will fix also.
