### ISSUE TITLE
Error: "No attachment found for service ___" 

### ISSUE THREAD

**Issue by ksanjaykumar1** [hyperledger/aries-framework-javascript#1480]
"No attachment found for service ___" Error is thrown when VC with multiple credential formats is offered. 

The error is thrown when the VC offer is accepted by the holder.  The error is thrown at the Issuer's end. 

![Screenshot from 2023-06-06 18-27-23](https://github.com/hyperledger/aries-framework-javascript/assets/72605368/6a5be7ef-ed04-45a1-b190-92e9ef77a9c8)

**Comment by genaris** [comment]
@ksanjaykumar1 are you using the released version of AFJ 0.4.0? This happened to me once when instantiating `CredentialsModule` with a `V2CredentialProtocol` that includes both `LegacyIndyCredentialFormatService` and `AnonCredsCredentialFormatService` but I thought we've fixed it some time ago.

**Comment by ksanjaykumar1** [comment]
I am using "0.4.0-alpha.130".
