### ISSUE TITLE
Cover Multi-Tenancy in the migration guide from 0.3.0 to 0.4.0

### ISSUE THREAD

**Issue by tarun-vadde** [hyperledger/aries-framework-javascript#1483]

**Comment by TimoGlastra** [comment]
Hey @tarun-vadde, can you add some context on your current step. How are you using multi-tenancy (for which roles, which flows, etc..), and also about your setup (are you using sqlite, postgres, what database mode are you using DatabasePerWallet, etc..)?

**Comment by tarun-vadde** [comment]
I'm currently using Postgres in Multi-Tenancy for learning purposes. I thought it would be a good idea if there were a guide on how to use the withTenantAgent method not just to create connections but also to issue credentials and verify proofs.
