### ISSUE TITLE
Does this repository alive?

### ISSUE THREAD

**Issue by djleonskennedy** [hyperledger/aries-framework-javascript#1493]
Hi Aries Team!

The main question about documentation, a lot of links are not available, like this [one](https://aries.js.org/guides/0.4/getting-started/updating/update-indy-sdk-to-askar)

There is no API page about agent, wallet methods, etc.

Do you plan to support it in the future at least?

**Comment by TimoGlastra** [comment]
Hey @djleonskennedy! 

The repository is very much alive. The documentation is not always fully up to date yet sadly.

Where did you find that link? It should point to here: https://aries.js.org/guides/0.4/updating/update-indy-sdk-to-askar

**Comment by djleonskennedy** [comment]
Hello @TimoGlastra, thank you for the answer

From Google search, I'm just trying to find an example of how to create DID in http://test.bcovrin.vonx.io

due the type it something like this, but I cannot find example in documentation

```
  const createdDid = async () => {
    agent?.dids
      .create<IndyVdrDidCreateOptions>({
        method: 'indy',
        options: {
          endorserMode: 'external',
          endorsedTransaction: {
            nymRequest: 'ENDORSER',
          },
        },
        secret: {
          seed: Buffer.from('your-seed-here'),
          privateKey: Buffer.from('your-privateKey-here'),
        },
      })
      .then(x => console.log('did:', x));
  };
```
