### ISSUE TITLE
Generating invitation and establishing connection

### ISSUE THREAD

**Issue by Shahriar707** [hyperledger/aries-framework-javascript#1494]
After reading Readme.md we figured out that “aries mobile agent react native”, part of the Aries Bifold project which was built on Aries Framework Javascript (AFJ). Now we have two questions regarding Aries Framework Javascript (AFJ):

Question-1: Can we create or generate an invitation so that one person can communicate with another one through the invitation using AFJ?

Question-2: Can we build or establish a connection between two different users using AFJ?

If we can create, then what are the best approaches for both of the above-mentioned questions?

**Comment by blu3beri** [comment]
1. yes.
2. yes.

The simplest way to do this is to follow this guide: https://aries.js.org/guides/0.4/tutorials/create-a-connection (and of course following the prerequisites). If something goes wrong during the tutorial, feel free to open a new issue.
