### ISSUE TITLE
schemaId undefined for registerCredentialDefinition using agent.modules.anoncreds.registerSchema

### ISSUE THREAD

**Issue by dnaicker86** [hyperledger/aries-framework-javascript#1505]
From the example https://aries.js.org/guides/0.4/tutorials/registering-schema-and-credential-definition#3-registering-a-schema

`const credentialDefinitionResult = await agent.modules.anoncreds.registerCredentialDefinition({
	credentialDefinition: {
	  tag: 'default:,
	  issuerId: '<did>',
	  schemaId: schemaResult.schemaState.schemaId,
	},
	options: {},
  })`

<img width="1459" alt="image" src="https://github.com/hyperledger/aries-framework-javascript/assets/130728803/6b108262-38b4-40ac-884c-0745ba1f94ee">

**Comment by blu3beri** [comment]
The return value might be undefined. If you add an assertion above or use `schemaId!` it should work. Feel free to reopen if it is not resolved.
