### ISSUE TITLE
CredentialEventTypes.OfferReceived does not exist for typeof CredentialEventTypes

### ISSUE THREAD

**Issue by dnaicker86** [hyperledger/aries-framework-javascript#1507]
From tutorial https://aries.js.org/guides/0.4/tutorials/issue-a-credential#3-listening-for-incoming-credentials the following error is displaying

```
holder.events.on<CredentialStateChangedEvent>(CredentialEventTypes.CredentialStateChanged, async ({ payload }) => {
    switch (payload.credentialRecord.state) {
      case CredentialEventTypes.OfferReceived:
        console.log('received a credential')
        // custom logic here
        await holder.credentials.acceptOffer({ credentialRecordId: payload.credentialRecord.id })
      case CredentialState.Done:
        console.log(`Credential for credential id ${payload.credentialRecord.id} is accepted`)
        // For demo purposes we exit the program here.
        process.exit(0)
    }
  })
```

<img width="1118" alt="image" src="https://github.com/hyperledger/aries-framework-javascript/assets/130728803/b90f8747-fe35-4638-8028-35da6dd9b98a">

**Comment by blu3beri** [comment]
hi! Thanks for reporting this issue. It actually should be `CredentialState.OfferReceived`, nice catch!

Would you like to create a PR for this in the docs? Otherwise I'd be happy to pick this up.

**Comment by dnaicker86** [comment]
@blu3beri apologies for late reply, I will try to create a pull request for the next one :)
