### ISSUE TITLE
Canary release broken after updates to CI

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1518]
The changes in #1500 somehow made the CI publishing fail. I think we need to enable verbose logging for lerna, as it doesn't print any useful information

**Comment by genaris** [comment]
It is probably an NPM authentication issue. I don't see any relevant change other than the fact that in previous setup-node action we were explicitly setting `registry-url` (to  'https://registry.npmjs.org/') while currently we left it on the default value (`''` according to [setup-node@v3 docs](https://github.com/actions/setup-node)). This makes the script to not write it in a .npmrc/.yarnrc file.

I'll create a quick PR to see if it does the trick.
