### ISSUE TITLE
did:key implementation in AFJ

### ISSUE THREAD

**Issue by Shahriar707** [hyperledger/aries-framework-javascript#1527]
Does AFJ support did:key method? 
If it does then what is the best way to implement it and it's documentation?

**Comment by berendsliedrecht** [comment]
Yes. You can register it on the dids module on the agent like so. 

```
...
dids: new DidsModule({
      registrars: [new KeyDidRegistrar()],
      resolvers: [new KeyDidResolver()],
    }),
...
```

**Comment by Shahriar707** [comment]
So we can build a connection between two people using did:key method?

**Comment by berendsliedrecht** [comment]
> So we can build a connection between two people using did:key method?
> 
> 

Yes.

**Comment by swcurran** [comment]
Not a DIDComm connection. did:key cannot have a service endpoint, so it can’t be used in a DIDComm connection.
