### ISSUE TITLE
Extract wallet handle from 'WalletAlreadyOpenedError' instead of throwing error on initialization

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#155]
Currently when initializing (mostly a problem on react native) the framework tries to open the wallet. If the wallet is already opened, it will throw an error. 

Looking at the NodeJS wrapper docs, the error thrown will contain the wallet handle of the already opened wallet. We should use that wallet handle instead of throwing the error.

https://github.com/hyperledger/indy-sdk/tree/master/wrappers/nodejs#openwallet--config-credentials----handle

```
-> handle: Handle (Number) - err: Error code handle: Handle to opened wallet to use in methods that require wallet access.
```

**Comment by TimoGlastra** [comment]
Seems like this is not possible after all

**Comment by icc-romeu** [comment]
How did you manage to work with this @TimoGlastra ? As every change makes RN to reload, and you get the error

**Comment by TimoGlastra** [comment]
See https://github.com/AbsaOSS/rn-indy-sdk/issues/41

I didn't get around to finishing it yet, but made a start.

**Comment by icc-romeu** [comment]
Fixed it, thx for the initial code: https://github.com/AbsaOSS/rn-indy-sdk/pull/47
