### ISSUE TITLE
Import error on iOS 

### ISSUE THREAD

**Issue by CarolineLCa** [hyperledger/aries-framework-javascript#1587]
Hello,

I'm testing import function but I noticed that when we put the wrong  backup password all the wallet stops working.

The import function calls react-native-fs copyFile, but for iOS the copyFile function returns an error when the destination file already exists as mentioned in their [Readme](https://github.com/itinance/react-native-fs#copyfilefilepath-string-destpath-string-promisevoid).

```
[WalletError: Error importing wallet 'walletId': “walletName.awlt” couldn’t be copied to “walletId” because an item with the same name already exists.]
```

Thanks!

**Comment by TimoGlastra** [comment]
Thanks for opening the issue @CarolineLCa.

Copying a wallet to a destination that already exists should fail, but maybe we need to improve the error handling for this.

Do you have an expected outcome of how this should work?

**Comment by CarolineLCa** [comment]
Hi @TimoGlastra 

I have tested the import function on Android and the file is overwritten by the new file being imported. The import function does this action using the [copyFile](https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/askar/src/wallet/AskarWallet.ts#L338-L339
) method. 

But on iOS it returns that error because copyFile can’t overwrite files there.

So, I was expecting that iOS would work the same way as Android.
