### ISSUE TITLE
Unable to build postgress plugin

### ISSUE THREAD

**Issue by djleonskennedy** [hyperledger/aries-framework-javascript#1612]
Hello Aries Team!

Trying to compile the Postgres plugin by using this [documentation](https://aries.js.org/guides/0.4/tutorials/indy-sdk-postgres-database-nodejs/macos)  have such error

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> /Users/yuriyyakovenko/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sockaddr.rs:156:9
    |
156 |         mem::transmute::<SocketAddrV4, sockaddr_in>(v4);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: `SocketAddrV4` (48 bits)
    = note: target type: `sockaddr_in` (128 bits)

For more information about this error, try `rustc --explain E0512`.
```

MacOS 

m1 processor 
Sonoma 14

cargo 1.68.2 (6feb7c9cf 2023-03-26)

Could you please help, Postgres is a main our storage tool

Regards

**Comment by sairanjit** [comment]
@djleonskennedy I think you have to build the plugin using the cargo version  `1.63.0` as there was an error while building with new versions and also same version is used in the GitHub actions as well [here](https://github.com/hyperledger/aries-framework-javascript/blob/main/.github/actions/setup-postgres-wallet-plugin/action.yml#L16)
