### ISSUE TITLE
react-native aries indy-sdk plugin agent setup

### ISSUE THREAD

**Issue by dnaicker86** [hyperledger/aries-framework-javascript#1620]
following tutorials from 
https://aries.js.org/guides/0.4/getting-started/set-up/aries-askar - askar agent: `yarn android` runs successfully 
https://aries.js.org/guides/0.4/getting-started/set-up/indy-sdk/react-native, https://github.com/animo/indy-sdk-expo-plugin - setup react-native expo plugin for indy-sdk libs

my code found here, for replication:
https://github.com/dnaicker86/aries-react-native-agent

after running `yarn android`:
```
yarn run v1.22.19
$ expo run:android
Error: The system cannot find the path specified.
Error: The system cannot find the path specified.
    at notFoundError (C:\Users\denai\Github\AriesJS\AwesomeProject\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\denai\Github\AriesJS\AwesomeProject\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at cp.emit (C:\Users\denai\Github\AriesJS\AwesomeProject\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

is this a plugin issue?

how do i get more info on why it failed?

node version 18, windows 11, git bash command line

**Comment by berendsliedrecht** [comment]
- The repository you linked does not contain any code.
- From just the error message it does not seem related to aries-framework-javascript
- Is there a specific reason why you want to use askar AND indy-sdk? Askar seems a bit redundant
- indy-sdk is officially deprecated from Hyperledger and we will move away from it, I'd recommend using askar/indy-vdr/anoncreds.

**Comment by dnaicker86** [comment]
Code is App.js
It is to just get a basic application to run in android.
The setup is the issue.

**Comment by dnaicker86** [comment]
- code is in app.js
- will remove indy-sdk usage
- thanks for the help

**Comment by dnaicker86** [comment]
@berendsliedrecht is https://aries.js.org/guides/0.4/getting-started/set-up/indy-vdr also deprecated and not recommended to use as well?

**Comment by berendsliedrecht** [comment]
No, just indy-sdk. Indy-vdr is part of the replacement for the indy-sdk for ledger interactions.

see: https://github.com/hyperledger/indy-sdk?tab=readme-ov-file#indy-sdk---deprecated
