### ISSUE TITLE
https://aries-mediator.animo.id/#/ is offline? Any other dev mediators? 

### ISSUE THREAD

**Issue by jack-robson** [hyperledger/aries-framework-javascript#1628]
I see https://aries-mediator.animo.id/#/ in Useful Resources section of https://aries.js.org/guides/0.4/tutorials/mediation but it looks to be offline.

Has it changed? I thought I saw a different one during my research but it escapes me right now.

**Comment by berendsliedrecht** [comment]
Also, looking at this part of the documentation (https://aries.js.org/guides/0.4/tutorials/mediation#2-recipient-alice-setup) it provides the correct URL in the example. Was there another place where you found that mistake of the ` https://aries-mediator.animo.id/#/` URL?

**Comment by jack-robson** [comment]
Can't believe I missed that last night.  😅 

I was getting the link from the bottom.

<img width="353" alt="Screenshot 2023-11-07 at 10 02 17" src="https://github.com/hyperledger/aries-framework-javascript/assets/143492403/3a06cbac-e94d-4267-bcb9-8ac80228834c">

**Comment by berendsliedrecht** [comment]
Ah, I see. I have created a PR https://github.com/hyperledger/aries-javascript-docs/pull/139 to remove this bad URL. Thanks for the catch!
