### ISSUE TITLE
Help needed to register webhook-url in AFJ based agents.

### ISSUE THREAD

**Issue by Sshovon** [hyperledger/aries-framework-javascript#1633]
In ACA-Py (Aries Cloud Agent Python), it is possible to specify and configure webhook URLs when creating wallets.  Is there a way to include webhook URLs when using an AFJ-based agent similar to how it's done in ACA-Py?

**Comment by TimoGlastra** [comment]
When using the AFJ Rest wrapper this is possible, however when using the Agent directly this is not part of the default features.

You can however very simply set this up yourself. Listen to the events you'd like to receive webhooks for, and whenever an event is emitted, you send the webhook to your desired URL. See for example the implementation in the rest wrapper: https://github.com/hyperledger/aries-framework-javascript-ext/blob/main/packages/rest/src/events/WebhookEvent.ts#L5-L17

It does miss some stability features such as retries. That's something you'd have to add still
