### ISSUE TITLE
Resolving 'Invalid Credential key correctness proof' Error in Distributed Credential Service Setup

### ISSUE THREAD

**Issue by jack-robson** [hyperledger/aries-framework-javascript#1634]
I have set up a credential issuing service on two separate machines with the intention to use the same cryptographic seed/DID/verkey on both. Initially, both machines could issue credentials without any issues.

However, after setting up and leaving the second machine in a different location, I encountered an 'Invalid Credential key correctness proof' error on the first machine. This error does not occur if I use a new seed/DID/verkey.

Could there be a file system element or a component I've overlooked that's necessary for operating the same seed/DID/verkey across multiple machines? Any guidance on making this work for more than one machine would be appreciated.

**Comment by jack-robson** [comment]
I wiped the key from where it was being saved, re-ran the service and it's working.

**Comment by TimoGlastra** [comment]
It depends a bit on the database you're using. But if you're using Postgres, it should be possible to use multiple machines. However, we're in the progress of removing Indy SDK and moving towards Aries Askar, which has some new feature which we're not fully leveraging yet (such as locking of files to prevent multiple processes overwriting each others' process) and transactions (to bundle writes to the database).

**Comment by jack-robson** [comment]
How would you use it on postgres on multiple machines?

Export and share the my issuer, i.e. "my-test-issuer" database?

Is there an easier way?
