### ISSUE TITLE
Do attribute values have to be strings? How do you handle objects? (AnonCreds)

### ISSUE THREAD

**Issue by jack-robson** [hyperledger/aries-framework-javascript#1640]
Can you store JSON inside credentials?

So far, I used JSON.stringify to encode my object into a single attribute.

I wondered if there was a better way? Nested attributes or something.

I tried searching but struggling to find anything to say either way.

Many thanks.

**Comment by djleonskennedy** [comment]
Technically you can put json as string as value but can’t imagine use case for that

**Comment by TimoGlastra** [comment]
In AnonCreds every value must be encoded to a number, which is signed. And currently the encoding scheme supports strings and numbers only.

You could "hack" it though by using e.g. dot notation (or JSONPath) notation. So you use a key of "user.first_name", etc.. If both sides understand this notation it works, but you do have to also register the properties like this in the schema and credential definition, and therefore it won't work for arrays (unless it's fixed length, so more like a tulple)

**Comment by TimoGlastra** [comment]
@berendsliedrecht how does AnonCreds v2 deal with nested structures?

**Comment by berendsliedrecht** [comment]
It does not seem to be natively supported. The only thing you could do would be the equivalent of your JSON path example. I do think that this can be quite essential for AnonCreds V2 so when I have the time, I will raise this issue.

**Comment by TimoGlastra** [comment]
> I do think that this can be quite essential for AnonCreds V2 so when I have the time, I will raise this issue.

Yes please do this. I think nested object and array support is very important, and one of the drawbacks of using AnonCreds at the moment

**Comment by swcurran** [comment]
Agreed about nested objects.  That is the same approach that, for example, JSON-LD RDF Canonicalization uses — converts everything into a list of messages.  The pathing approach would be used for Indy.  Selective disclosure becomes interesting, as it should be possible to select and disclose an level of the item — e.g. the entire structure, or the nested elements within the structure.

I also think that given the signatures schemes that are planned for AnonCreds v2 (BBS+ and PS signatures), arrays could also be supported.  I’ve always thought that the biggest challenge with supporting arrays is what to do with selective disclosure. In thinking about it, I think we should support either disclosing the entire array, or the selected items from all the rows of the array.

Of course if the array items have different elements per entry….
