### ISSUE TITLE
Anoncreds attributes types.

### ISSUE THREAD

**Issue by sudddy** [hyperledger/aries-framework-javascript#1645]
Hello, 

`Question 1`: Are there any other types in the attributes other than string?  If not, are there any plans to add it in the future? 
`Question 2`:  How do the documents get saved in the chain? Do we need to store the documents in our own server and reference them to a did?

**Comment by berendsliedrecht** [comment]
1. Numbers are also supported, but that is about it. Anoncreds V2 might change that, but it is unsure. 

2. That depends on the did method. For a blockchain based did method, you store the entire did document on chain. For something like did:web you would host the entire document on your server. 

Hope that helps.

**Comment by sudddy** [comment]
Thanks for your quick reply 🙏  @berendsliedrecht  - Do we have a library that supports storing documents on chain or is it yet to be implemented?

**Comment by berendsliedrecht** [comment]
Something like hyperledger/indy-vdr could do that.
