### ISSUE TITLE
wallet import and export

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#175]
Add feature to import and export wallet.

First iteration should just import / export the indy wallet. Next iterations could focus on more interoperable data format

RN indy sdk code already available here: https://github.com/AbsaOSS/rn-indy-sdk/pull/57. Should be merged into indy-sdk-react-native

**Comment by standlove** [comment]
Hi, @TimoGlastra 

Is there any plan when this can be completed?

Thanks
