### ISSUE TITLE
Credentials have no easy way to access its attributes

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#187]
Currently when you have a credential record it is not easy to access its attributes. You need to either:

- parse the preview from the offer message
- parse the raw values from the credential message
- retrieve the credential from indy storage

Aries Framework .NET just stores the attributes in the record. I think we should do the same

**Comment by jakubkoci** [comment]
I'm still curious if it's possible to utilize `credentialPreview` for that

**Comment by TimoGlastra** [comment]
I think that's doable. We can add a connivence method to the credential record that returns the credential preview (or something else based on the credential preview)

**Comment by jakubkoci** [comment]
My concern is security. I'm not sure if the user can rely on data in `credentialPreview`, because it could differ from data in actual `credentialOffer/credenital`.

**Comment by TimoGlastra** [comment]
Well it should be trustable. If the issuer makes an offer, the holder requests it and then issues a different credential it should throw an error and not acknowledge it.

If we don't reject that at the moment, we should add a check for it.

**Comment by jakubkoci** [comment]
Hmm. I assumed that libindy takes care of consistency between credOffer, credReq and cred, therefore we wouldn't need to validate if the received credential matches the offer. Then we just would need to validate `credentialPreview` against `credentialOffer` and stores the `credentialPreview` as attribute in `credentialRecord`

**Comment by TimoGlastra** [comment]
How to format credentials: 

```jsonc
{
	// metadata contains credentials format specific stuff
	"metadata": {
		"credentialDefinitionId": "creddefid"
	}
	"claims": {
		"name": "name"
	}
}
```

I'll add a few utility methods such as returning the attributes in a properly cased or returning them alphabetically

@JamesKEbert thoughts?

**Comment by JamesKEbert** [comment]
I think as you've proposed is great. 👍
