### ISSUE TITLE
Add auto-acceptance to present-proof protocol

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#194]
Basically the same as #60 and #116 but for proofs.

Checklist:

 - add option to enable / disable auto-accept of proofs
	 - [ ] in agent config
	 - [ ]  to credential record
	 - [ ]  to credential service methods
	 - [ ]  to credential module methods

**Comment by TimoGlastra** [comment]
@blu3beri

**Comment by blu3beri** [comment]
Yes, will pick this up!
