### ISSUE TITLE
Rename `CredentialRecord` and `ProofRecord` to `CredentialExchangeRecord` and `PresentationExchangeRecord`

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#199]
We've had discussions about this before and I'm not sure why we didn't go with the exchange naming. Mainly why I'm bringing it up again is because the current API is confusing. 

We have a `CredentialRecord` that contains an `id` and `credentialId` where the `id` is the id of the credential record and the `credentialId` maps to the indy credential id. It's confusing.

By calling it a credential exchange record it's more clear: The credential exchange record has an `id`. This is the id of the credential exchange. It also has a `credentialId` which maps to the credential. 

Another thing why I think we should call it exchange is future proofing. If we're going to add support for non-indy credentials we need to add a record to store these credentials. `CredentialRecord` would be a good match I think.

@jakubkoci If I remember correctly, you were against this last time we discussed. I'd like to hear your opinion on it

**Comment by jakubkoci** [comment]
I see. The reasoning behind certainly makes sense in the way that the  `CredentialRecord` actually records the exchange of issue credential protocol messages. But let me just show some examples if I understand the change:

```js
class CredentialRecord {
	id: number,

  // represents relation CredentialRecord -> Credential
  credentialId: number 
}

class Credential {
	id: number,
}
```

Do I understand correctly you’re suggesting the following update:
```js
class CredentialExchangeRecord {
	id: number,

  // represents relation CredentialExchangeRecord -> Credential
  credentialId: number
}

class Credential {
	id: number,
}
```

Maybe let's look at some examples of the API calls. I can imagine this one:
```js
const credentialRecord = await agent.credentials.getById(credentialRecord.id);
await agent.credentials.acceptOffer(credentialRecord);
```

vs.
```js
const credentialExchangeRecord = await agent.credentials.getById(credentialExchangeRecord.id);
await agent.credentials.acceptOffer(credentialExchangeRecord);
```

**Comment by JamesKEbert** [comment]
I agree with @TimoGlastra that the current API is confusing--as of right now the differences between `id` and `credentialId` are not naturally apparent. I think your API example @jakubkoci could lead to revealing some of the benefits that changing the naming convention.

API as an example/proposal:
```ts
const credentialExchangeRecord = await agent.credentials.exchange.getById(credentialExchangeRecord.id);
await agent.credentials.exchange.acceptOffer(credentialExchangeRecord.id);

const credentialRecord = await agent.credentials.getById(credentialRecord.id);
//Display Credential
credentialRecord.attributes.map(() => { ... };
```

To compare the two points of view, as you have suggested @jakubkoci (as I understand):
```ts
//Credential Exchange Record
agent.credentials.getById(id) 
//Credential Record
agent.credentials.getById(id)
```

I personally think the above calls end up being ambiguous and confusing as to what the differences are between the two (as the only differences are in what they return). I think that adding an additional layer to the module/API definitely makes it immediately clearer as to how this is to be used. 
```ts
agent.credentials.exchange.getById(id) 
agent.credentials.getById(id)
``` 
\
\
You could even have the credential be at that sublevel as well, which could potentially be beneficial for future work (such as revocation?) or code structure-wise:
```ts
agent.credentials.exchange.getById(id) 
agent.credentials.credentialRecord.getById(id)
agent.credentials.revocation.revokeCredentialById(id)
```

One benefit here that comes as an outcome is that we can likely more easily split out the credential Record validation into it's own class--which could help address #187.

**Comment by jakubkoci** [comment]
I'm just putting the full example of API from my perspective for comparison while thinking through your suggestions :)

```js
// I want to get credentialRecord to accept offer
const credentialRecord = await agent.credentials.getRecordById(credentialRecord.id);
await agent.credentials.acceptOffer(credentialRecord.id);

// I want to show credential details in UI
credentialRecord.attributes.map(() => { ... };

// I need the Indy credential itself for some other reasons (integration tests according to AIP for example)
const credential = await agent.credentials.getById(credentialRecord.credentialId);
```

**Comment by TimoGlastra** [comment]
I agree with @JamesKEbert on this one, and really like the nesting for categorization. 

@jakubkoci The distinction you make between `Credential` and `CredentialRecord` is not clear to me. To me they both indicate a credential. Where one may be the storage format, and the other the processing format. E.g. in ACA-Py we now have a VCRecord that stores the VC, adding tags and other stuff for it to be searchable from storage. After retrieving it from storage it is parsed to a VerifiableCredential class that represents the actual structure of a verifiable credential, not the storage structure of the credential.

Maybe I'm too deep into the ACA-Py architecture, but I just can't interpet the difference between `Credential` and `CredentialRecord` as you mean. Especially when looking at the API.

IMO this (from James comment) leaves so much less to the imagination, and assumption capabalities of the developer or framework consumer

```ts
agent.credentials.exchange.getById(id) 
agent.credentials.credentialRecord.getById(id)

// maybe this
agent.credentials.getById(id)
// agent.credentials.revocation.revokeCredentialById(id)
```

than this:

```ts
const credentialRecord = await agent.credentials.getRecordById(credentialRecord.id);
const credential = await agent.credentials.getById(credentialRecord.credentialId);
```

**Comment by jakubkoci** [comment]
```ts
// I want to get credentialRecord to accept offer
const credentialExchangeRecord = await agent.credentials.exchange.getById(credentialExchangeRecordId);
await agent.credentials.exchange.acceptOffer(credentialExchangeRecord.id);

const credentialRecord = await agent.credentials.record.getById(credentialExchangeRecord.credentialRecordId);
// I want to show credential details in UI
credentialRecord.attributes.map(() => { ... };

// I need the Indy credential itself for some other reasons (integration tests according to AIP for example)
const credential = await agent.credentials.getById(credentialRecord.credentialId);
```

**Comment by jakubkoci** [comment]
I’ve been studying Domain-Driven Design lately and I realized that maybe we could apply some ideas from that. 
* What if we do not expose `Record` classes at all? 
* What if we put together data from `CredentialRecord`  and `IndyCredential` when the user asks for credential(s)?

To me, it’s weird to have the following API because I get a `Record` from both but `recrods` is mentioned only in on of them:
```ts
const credentialExchangeRecord = await agent.credentials.exchanges.getById(credentialExchangeRecord.id);
const credentialRecord = await agent.credentials.records.getById(credentialRecord.id);
```

We would have something like this instead:
```ts
const credentialExchange = await agent.credentials.exchanges.getById(credentialExchange.id);
const credential = await agent.credentials.getById(credential.id);
```

Every repository would need to transform/convert `Record` from/to a domain object. Domain object wouldn't need to contain `tags`, which is duplicated information anyway.

Open Issues:
* I’m still not sure how the `Credential` domain object should look in relation to `CredentialInfo`/`Cred`. 
* It’s a question of how searching wallet for credentials when calling `credentials.getAll()` can impact performance. It could be partially solved by prohibiting to call `getAll()` and allow only calling it with some filter `findByFilter(filter)`   plus add `getAllMetadata()` which would return objects without `IndyCredential` itself.
