### ISSUE TITLE
Remove MessageType enums and use classes directly instead

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#200]
I would suggest removing MessageType enums and put the message type string directly into the message class which represents this type anyway and it is according to the open-close principle, we can add a type by adding a class and we don't have to change MessageType enum.

If you agree I'm happy to create PR.

**Comment by TimoGlastra** [comment]
There are a few places where we use the message enums directly, but I guess we can refactor them to use them type property on the message classes.

So yeah, fine by me
