### ISSUE TITLE
Mediator coordination protocol recipient role

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#203]
Add mediator coordination protocol as recipient role.

Keylist update is already implemented. But the request mediation parts still need to be implemented. 

**Resources:**
- flow: https://github.com/hyperledger/aries-framework-javascript/issues/40
- https://github.com/hyperledger/aries-rfcs/blob/master/features/0211-route-coordination/README.md
- Issue for mediator role: #63

**Comment by TimoGlastra** [comment]
@JamesKEbert I'm not able to assign you, but created this issue to track the recipient role part of the protocol

**Comment by JamesKEbert** [comment]
Perfect, thank you. We'll start digging in and working on this!

**Comment by TimoGlastra** [comment]
Fixed!
