### ISSUE TITLE
Pass a Genesis string to agent config instead of a file path

### ISSUE THREAD

**Issue by icc-romeu** [hyperledger/aries-framework-javascript#219]
Currently the agent receives a genesisPath to a file. This is not convenient for dynamic configurations. It should be able to receive a string.

If a genesis file is included it is trivial to read it and pass the resulting string.

**Comment by jakubkoci** [comment]
I'm afraid that indy-sdk requires path to file according to [createPoolLedgerConfig](https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/README.md#createpoolledgerconfig--configname-config----void).

I don't know why or if it's really necessary 🤷‍♂️

**Comment by icc-romeu** [comment]
I have done a trick for that, use the native part of the library -I work on react native- to create a "temporary" file to init the Indy library. I know this is a "hack" but it makes sense for me not to "force" the user to have a file when the library only needs the content. 

I think this is an implementation detail of Libindy that should be hidden. But I admit it is a convenience issue, not a "must".

**Comment by TimoGlastra** [comment]
I agree! I already allowed to pass a url in the mobile wallet. Problem is that storage depends on the environment. This means we need to add RN specific + nodejs specific code and libraries to the framework which is not that ideal...

**Comment by karimStekelenburg** [comment]
Does anyone know if there are plans to change this in Indy? If not a possible solutions is to abstract it away from the framework. For example define something like a `GenesisProvider` interface where its implementations are responsible for handling the platform specific storage stuff. 

That being said, it's not a sexy solution either, so it might be worth opening an issue on the Indy side of things, since we all don't seem to understand the reasoning behind it...

**Comment by icc-romeu** [comment]
@karimStekelenburg it's easy to solve in javascript/typescript. I used a couple of convenience methods -copied from @TimoGlastra who wrote them [here](https://github.com/animo/aries-mobile-agent-react-native/blob/develop/src/agent/genesis-utils.ts)- and then you can pass a path to a file, a url to download the file or the string itself. 

Maybe we could include this in this framework? 🤷🏻‍♂️ Hence we will hide this implementation detail to final users

```
          let genesisPath = props.agentConfig.genesisPath;
          if (props.agentConfig.genesisUrl) {
            const genesis = await downloadGenesis(props.agentConfig.genesisUrl);
            genesisPath = await storeGenesis(genesis, 'genesis.txn');
          } else if (props.agentConfig.genesisString) {
            genesisPath = await storeGenesis(
              props.agentConfig.genesisString,
              'genesis.txn',
            );
          }
```
