### ISSUE TITLE
Babel: plugin-proposal-async-generator-functions needed to use framework

### ISSUE THREAD

**Issue by icc-romeu** [hyperledger/aries-framework-javascript#228]
I was struggling with a problem using the framework in React Native. I was getting this error:

```TypeError: Invalid attempt to iterate non-iterable instance.```

As the framework is using async generators, ```@babel/plugin-proposal-async-generator-functions``` plugin needs to be included, as Babel does not support them by default. I think this should appear in the README.md or wherever you think it is appropriate.

This [comment](https://github.com/repeaterjs/repeater/issues/68#issuecomment-782762102) explains how to solve it.

To add the plugin, install it:

```yarn add --dev @babel/plugin-proposal-async-generator-functions```

then add to babel.config.js:

```
module.exports = {
    presets: ["module:metro-react-native-babel-preset"],
    plugins: [
        ["@babel/plugin-proposal-async-generator-functions"],
    ],
}
```

**Comment by TimoGlastra** [comment]
We just solved an issue related to this yesterday. 

See https://github.com/hyperledger/aries-framework-javascript/issues/225 and https://github.com/hyperledger/aries-framework-javascript/pull/226. Are you using the latest commit of the framework?

**Comment by TimoGlastra** [comment]
Or is this not related to that?

**Comment by icc-romeu** [comment]
No, I am not using yesterday's branch. 😬

I think it is related @TimoGlastra. It has to do with Babel. But it is solved with the fix I posted. Babel includes it with that plugin and no more issues.

P.D.: I promise to search for issues before posting a new one next time 😅

**Comment by TimoGlastra** [comment]
Could you verify if the plugin is still required with the latest version of the framework. Curious if this needs further investigation / fixes / documentation updates or that it can be closed with the fix from yesterday

**Comment by icc-romeu** [comment]
I have updated to the last version, and removed the Babel plugin and it works. The credentials and connections iterate correctly, so we can close this.
