### ISSUE TITLE
Expose decorators vs generated interfaces

### ISSUE THREAD

**Issue by icc-romeu** [hyperledger/aries-framework-javascript#229]
I have built the framework with "npm pack" and I'm using it with that way. I have noticed a weird behaviour on interfaces and decorators. 

For example, at ```OfferCredentialMessage``` the generated interface is this:

```
export declare class OfferCredentialMessage extends AgentMessage {
    constructor(options: OfferCredentialMessageOptions);
    readonly type = IssueCredentialMessageType.OfferCredential;
    static readonly type = IssueCredentialMessageType.OfferCredential;
    comment?: string;
    credentialPreview: CredentialPreview;
    attachments: Attachment[];
    get indyCredentialOffer(): CredOffer | null;
}
```

but, at run time the debugger tells me that ```offerMessage``` in the ```CredentialRecord``` contains this:

```
{
  "@type": "https://didcomm.org/issue-credential/1.0/offer-credential",
  "@id": "eeee0846-6fbe-4117-947c-x",
  "~thread": {},
  "offers~attach": [
    {
      "@id": "libindy-cred-offer-0",
      "mime-type": "application/json",
      "data": {
        "base64": <long base64>
      }
    }
  ],
  "credential_preview": {
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/credential-preview",
    "attributes": <some attributes>
  }
}
```

Which is an Indy message, but does not conform to interface... Hence, the IDE complains if I try to access any of those fields.

Which is the right way of accessing the information of that offer?

**Comment by icc-romeu** [comment]
Ok, ignore it... I just found out how to:

```let offer = JsonTransformer.fromJSON(credentialRecord.offerMessage, OfferCredentialMessage)```

But maybe this should be documented somewhere in a "how to use the framework".

**Comment by TimoGlastra** [comment]
Yup we really need some documentation on this
