### ISSUE TITLE
Wait for a response when creating a route for a new connection in a mediator.

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#234]
Currently, we don't wait for a response when we're creating a route for a new connection in a mediator. 

We just call `await this.consumerRoutingService.createRoute(connectionRecord.verkey)` in `ConnectionsModule`.

We should wait for the response from the mediator before we proceed. This requires the implementation of  `KeylistUpdateResponseHandler` and then somehow notifying about the result to the `ConnectionsModule`.

**Comment by TimoGlastra** [comment]
@jakubkoci this is fixed now right?

**Comment by TimoGlastra** [comment]
@jakubkoci is this fixed?

**Comment by TimoGlastra** [comment]
This is fixed now!
