### ISSUE TITLE
Use conventional commits for easier releases, better changelogs

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#235]
The most cumbersome part of the release flow to me seems like the manual creation of a release, gathering the changes since the last release to write a changelog. See which version to choose.

I'd like to propose to use conventional commits so we can fully automate the release process. This will require some extra work from us at commit time, but this is only a little bit if you compare it to the overall work of creating releases IMO.

To quote:
> In open source projects we have to be super productive because we often work in our time, after hours. Productivity is everything. Automation is the essential ingredient for productivity. Semantic release expects discipline from your team to write commit messages according to the conventional changelog standards. The positive outcome is a fully automated and modern development workflow.

We're already doing this a bit with the `fix`, `style`, `refactor` prefixes. Just need to consistently do this. We can also add tools to assist with this. Main question is whether everyone thinks it is beneficial to take up this extra burden

**Comment by jakubkoci** [comment]
I agree. We can at least start and get used to that.
