### ISSUE TITLE
ISO Date Parsing Failure in React Native

### ISSUE THREAD

**Issue by JamesKEbert** [hyperledger/aries-framework-javascript#301]
I uncovered an issue just a little bit ago with ISO date parsing in React Native. When receiving basic messages, we perform `new Date(sentTime).toISOString()`. Unfortunately the date parsing involved here was not universally standardized effectively in JS, and so therefore this operation is incompatible in React Native with timestamps in ISO 8601 UTC ("2019-01-15 18:42:01Z"), unless it contains a `t` instead of a space.

See this stackoverflow for additional context: https://stackoverflow.com/questions/13363673/javascript-date-is-invalid-on-ios/13363791

I am not initially sure the best approach to resolving this issue, but I can dig in more. I would prefer to not introduce an entirely separate package to accomplish just this, and wonder if we can do some kind of polyfill or compilation change.

**Comment by TimoGlastra** [comment]
```ts
"2019-01-15 18:42:01Z".replace(" ", "T") // :-)
```

No we should see to properly fix this. Maybe a polyfill that we only use on React Native? As that seems to be the evil-doer
