### ISSUE TITLE
Node 16.3.0 breaks CI tests

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#309]
Node 16.3.0 was released four days ago and now the CI is failing with this specific Node version.

Running with Node 16.2 again fixed the issue (https://github.com/hyperledger/aries-framework-javascript/runs/2753075392?check_suite_focus=true). 

I've also rerun the CI of #304 (https://github.com/hyperledger/aries-framework-javascript/runs/2753068469?check_suite_focus=true) and that also seems to be failing with 16.3

_Originally posted by @TimoGlastra in https://github.com/hyperledger/aries-framework-javascript/issues/303#issuecomment-855243034_

**Comment by blu3beri** [comment]
@TimoGlastra Is this still an issue?

**Comment by TimoGlastra** [comment]
Not sure. I think we could try by testing for `16.x` again which should pick 16.13.0 now. We could also add Node 17 to the test matrix

**Comment by blu3beri** [comment]
> Not sure. I think we could try by testing for `16.x` again which should pick 16.13.0 now. We could also add Node 17 to the test matrix

I think that adding 17.x might be nice as it is the latest. But not too sure if we want to replace 12 or 16 or add it.

**Comment by TimoGlastra** [comment]
I'd say let's add it. They run in parallel so doesn't add too much time to the CI process and thin it would be good to know when we break something
