### ISSUE TITLE
Framework compatibility and Credentials support

### ISSUE THREAD

**Issue by Nilang** [hyperledger/aries-framework-javascript#32]
Hello,

I understand that this project is in very early stages compared to [aries dotnet framework](https://github.com/hyperledger/aries-framework-dotnet) and other aries projects. However, I am curious to know if there are there any plans with this project to make it compatible with frontend frameworks like React, Angular or Vue? and if there is any timeline to add credentials support in terms of validating proofs and revocation. 

Thanks

**Comment by jadhavajay** [comment]
As of now there is not timeline set for credentials support, but we hope to plan it in our upcoming bi-weekly meetings, starting after HGF tentatively on 20th March.

**Comment by Nilang** [comment]
Thank you!
