### ISSUE TITLE
Error: Connection record is not ready to be used

### ISSUE THREAD

**Issue by MosCD3** [hyperledger/aries-framework-javascript#337]
I am using agent 'Bifold' which is build using this framework

I am trying to get Bifold to accept an invitation sent by a DTS issuer running on my local machine
I cannot get pass this error after scanning the barcode of the credential invitation
[javascript] Possible Unhandled Promise Rejection (id: 0):
Error: Connection record is not ready to be used. Expected responded or complete, found invalid state requested
Error: Connection record is not ready to be used. Expected responded or complete, found invalid state requested

Steps:

Run bifold
Connected to mediator success
Run dts local issuer
https://github.com/bcgov/dts-vc-issuer-service
Generate vaccination credential
Scan credential with bifold
The wallet switches to 'connecting'
Nothing happens from there
Just to make things easier
this is the last message received from issuer right before the exception happens

{
  "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/offer-credential",
  "@id": "cfb0d143-0705-41ec-8d1d-74ae3945f934",
  "~thread": {},
  "offers~attach": [
    {
      "@id": "libindy-cred-offer-0",
      "mime-type": "application/json",
      "data": {
        "base64": "[Base 64 data]"
      }
    }
  ],
  "credential_preview": {
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/credential-preview",
    "attributes": [
      {
        "name": "name",
        "value": "Vaccination Certificate"
      },
      {
        "name": "description",
        "value": "Vaccination Certificate"
      },
      {
        "name": "expirationDate",
        "value": "2022-06-30T04:46:57.6417668+00:00"
      },
      {
        "name": "credential_type",
        "value": "VaccinationEvent"
      },
      {
        "name": "countryOfVaccination",
        "value": "CA"
      },
      {
        "name": "recipient_type",
        "value": "VaccineRecipient"
      },
      {
        "name": "recipient_fullName",
        "value": "SCHITT, Roland Ethan"
      },
      {
        "name": "recipient_birthDate",
        "value": "01/14/1952"
      },
      {
        "name": "vaccine_type",
        "value": "Vaccine"
      },
      {
        "name": "vaccine_disease",
        "value": "Influenza"
      },
      {
        "name": "vaccine_medicinalProductName",
        "value": "Fluzone High-Dose"
      },
      {
        "name": "vaccine_marketingAuthorizationHolder",
        "value": "SANOFI PASTEUR LIMITED"
      },
      {
        "name": "vaccine_dateOfVaccination",
        "value": "09/22/2020"
      }
    ]
  },
  "comment": "create automated credential exchange"
}

I attached the log from both the issuer and the bifold terminal

[agent_invitee.txt](https://github.com/hyperledger/aries-framework-javascript/files/6738256/agent_invitee.txt)
[issuer_log.txt](https://github.com/hyperledger/aries-framework-javascript/files/6738258/issuer_log.txt)

I also can't seem to find clear documentation for how to build a controller on top of this framework

Any more thoughts?

**Comment by TimoGlastra** [comment]
Hi @MosCD3, thanks for raising this issue!

I think you're running into the following issue: https://github.com/hyperledger/aries-framework-javascript/issues/259. I'll see to quickly make a fix to resolve it.

the connection response and credential offer are both sent to the mediator. The mobile agent then picks those up in a batch and processes them in parallel instead of serial.

**Comment by TimoGlastra** [comment]
Re the documentation. There's not that much documentation yet. We're working hard to improve both the framework and the documentation. 

We have getting started guides, but those are only partly finished at the moment. I'll make a ticket to update them
