### ISSUE TITLE
Migrate Web Agent Sample to NestJs 

### ISSUE THREAD

**Issue by jadhavajay** [hyperledger/aries-framework-javascript#34]
As discussed previously in one of our community calls, I propose to migrate the current source code structure to [NestJs ](https://docs.nestjs.com/cli/monorepo)based code organization structure in order to have a convention based approach to the architecture. Also it will help new contributors to follow well-defined coding patterns.

**Comment by jakubkoci** [comment]
That's a good idea. We need to be aware that Nest.js is primarily a server-side, backend oriented framework, but it could be nice to have Nest.js DI container for example. I did a demonstration of minimal setup using DI container in [nest-di](https://github.com/jakubkoci/nest-di) project (see  [main.ts](https://github.com/jakubkoci/nest-di/blob/master/main.ts) file).

**Comment by jadhavajay** [comment]
Yes, we can separate out the library oriented modules and server hosted modules so that we can achieve re-usability of library modules across the target platforms such as React-Native, Node, etc.

I am working out a project structure and will share it soon with you guys once ready.

**Comment by TimoGlastra** [comment]
I'm closing this. We can create a new issue once we decide to implement dependency injection / have a concrete plan
