### ISSUE TITLE
Add support for receiving and proving revocable indy credentials

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#349]

**Comment by TimoGlastra** [comment]
@JamesKEbert assigning you. This is only the receiving and proving part. #112 tracks the whole flow

**Comment by swcurran** [comment]
A reminder -- because it's been a pain.

- A proof request that includes a revocation interval can be satisfied with a non-revocable credential.
- A proof request that does not include a revocation interval can be satisfied with a revocable credential.

LISSI and estatus support this correctly, Trinisic still does not.

**Comment by JamesKEbert** [comment]
@swcurran revocation intervals in Indy can be specified on an attribute/predicate basis, is this something generally supported by the community, or is it sufficient to use the proof request's top level revocation interval?

**Comment by swcurran** [comment]
I'm not aware of anyone using them, but all of that is handled in the Indy SDK (or indy-shared-rs) and so should "just work" if the conventions are followed.  See: https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0441-present-proof-best-practices for what conventions are to be followed -- with the big thing being the from/to range to give the Indy proof request.

**Comment by TimoGlastra** [comment]
@JamesKEbert what's the status of this? If you're not able to finish it, maybe you can post what's already there so someone else can pick it up?

**Comment by JamesKEbert** [comment]
@TimoGlastra, sorry for any delays here--I actually have been making good progress on this, I expect to have a PR this week. I have a couple of things that might be good to discuss, so maybe during the AFJ call tomorrow some discussion time might be good?

**Comment by TimoGlastra** [comment]
@JamesKEbert as part of the revocation work, are you also picking up the revocation notification protocol (#493)? There is someone else that might work on it, if you're not working on it already

**Comment by JamesKEbert** [comment]
Yes, we are, we've only implemented the holder side of the protocol though. I figure when the efforts for the issuer-side happen we may be to a new iteration of the protocol anyways.

**Comment by TimoGlastra** [comment]
That's great. Thanks James :)
