### ISSUE TITLE
Add support for 0453: Issue Credential v2

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#352]
https://github.com/hyperledger/aries-rfcs/tree/b3a3942ef052039e73cd23d847f42947f8287da2/features/0453-issue-credential-v2

**Comment by NB-MikeRichardson** [comment]
I have started the development of this RFC.

**Comment by NB-MikeRichardson** [comment]
Can someone assign this to me?

**Comment by TimoGlastra** [comment]
You got it!

**Comment by NB-MikeRichardson** [comment]
That was quick!

Cheers
Mike
