### ISSUE TITLE
Add support for 0454: Present Proof v2 

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#353]
https://github.com/hyperledger/aries-rfcs/tree/b3a3942ef052039e73cd23d847f42947f8287da2/features/0454-present-proof-v2

**Comment by NB-PrasadKatkar** [comment]
Hi @TimoGlastra , I would like to start working on this ticket. Can you please assign this to me. Thanks

**Comment by TimoGlastra** [comment]
You got it!
