### ISSUE TITLE
Agent failed to connect - undefined is not a function

### ISSUE THREAD

**Issue by gilAsier** [hyperledger/aries-framework-javascript#373]
I am trying to get the agent connected, but I getting this error:
[TypeError: undefined is not a function]

The code I am running is: 
![image](https://user-images.githubusercontent.com/4936241/125275662-9b08ec80-e30f-11eb-8673-041c4dc930de.png)

I don't know what it takes to make it work. Any ideas?

Thanks

**Comment by TimoGlastra** [comment]
Hi @gilAsier! Thans for opening the issue.

The `init` method was recently changed to `initialize`, but this has been updated in the docs. I opened #374 to update this.

Could you try again with `initialize` instead of `init`?

**Comment by gilAsier** [comment]
Nice, thats's work now.
Thanks you @TimoGlastra.
