### ISSUE TITLE
Allow storing unpacked messages in the message queue

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#379]
Currently we can only store packed messages in the message queue. Sometimes we need to store unpacked messages in the message queue (e.g. if we want to send a message, but don't know which key to use for packing yet)

We should support storing unpacked messages in the queue, then when the message is taken from the queue pack it with the correct keys used for the used service (based on the senderKey of the message that opened the socket)

**Comment by burdettadam** [comment]
I think this is related to #383

**Comment by TimoGlastra** [comment]
Code is refactored to already pack the message. Queue transports endpoint defines the key to use for packing, so we can already determine which keys to use for queuing.
