### ISSUE TITLE
passing mediatorConnectionsInvite does not provide best DX

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#381]
I'm really a fan of the mediatorConnectionsInvite, but the flow it introduces is a bit quirky IMO.

On first launch I want to provide the `mediatorConnectionsInvite` to connect to the mediator. It will then connect and set the mediator as default. All good. Next launch I don't want to pass the `mediatorConnectionsInvite` because I'm already connected and have it assigned as default mediator.

Now I need to track outside of the agent whether I already connected to this mediator. 

What if, on startup, we first look up the mediation/connection record and see if the invitation (or the keys, or something else) matches and if so do not connect, because we're already connected.

cc @burdettadam

**Comment by burdettadam** [comment]
I am glad we are at this discussion. I think checking if we have created a connection with the provided invitation before attempting to reconnect is the way to go. We should probably check if the connection was accepted and if a request for mediation has been granted, and then set that mediator as default. 
Do we track the invitation a connection is made with. then we could search all connections for one that has a matching invite.
If we get all mediated connections and search for a connection created by that invitation, we will implicitly know if a connection has been made and mediation granted. 
I think this feature (multiple restarts with the same `mediatorConnectionsInvite` config does not produce multiple mediated connections) is needed and I have no bias in how we implement it.

**Comment by TimoGlastra** [comment]
Fixed in #419
