### ISSUE TITLE
ProofService.createProof expects non-standard input object

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#382]
As a consequence of the changes made in #329, the `ProofService.createProof` method now expects the `RequestedCredentials` object to have a `credentialInfo` property. This is added in the `getRequestedCredentialsForProofRequest`, but is not a default property on the object.

In updating AATH we've noticed that we create the requested credentials outside of the framework because we already have the credential ids, meaning we don't call this method.

So my question is basically, is what were doing not the default approach and should thus handle this outside of the framework, OR should we take this into account in the createProof method and retrieve the credential info if not attached yet.

I'd lean toward the second option, but I'm interested to hear your opinion on this.

cc @TheTreek @JamesKEbert

**Comment by JamesKEbert** [comment]
So if I understand correctly, the issue here isn't that `credentialInfo` is present, it's that the AATH doesn't have it in its tests. I am open to the second option, however I am curious if the AATH could use the AFJ methods available to get the requested credentials? 
And @TheTreek and I are working in this area already so we likely could make needed fixes here once decided upon a solution.

**Comment by TimoGlastra** [comment]
Yes! AATH passes the requested credentials object to the backchannel, so no need to call the method that attaches `credentialInfo`. We've added a workaround in AATH for now.

I think we should extend the method in createProof to first check if `credentialInfo` is present (And make it optional on the class). If not present, fetch it in the method.

**Comment by JamesKEbert** [comment]
Awesome, @TheTreek and I will look to make this change then. 👍

**Comment by blu3beri** [comment]
@JamesKEbert any update on this?

**Comment by JamesKEbert** [comment]
I am _actually_ working on revocation today, so yes this should be covered under that scope of work!

**Comment by TimoGlastra** [comment]
Fixed in #592
