### ISSUE TITLE
Online mediator issues

### ISSUE THREAD

**Issue by MosCD3** [hyperledger/aries-framework-javascript#394]
I am having problems getting past the mediator init
first do I need each build to hit the "https://mediator.animo.id/invitation" to get an updated invitation ?!!

Next once you get a invitation link and past it to the config 

const agentConfig: InitConfig = {
      label: 'my-agent2',
      mediatorConnectionsInvite: 'Invitation link',
      walletConfig: {id: 'walletId2'},
      walletCredentials: {key: 'testkey0230482304823042304236'},
      autoAcceptConnections: true,
      poolName: 'test-186',
      genesisPath,
      logger: new ConsoleLogger(LogLevel.debug),
    };

it works ONLY for the first build
next build you get 505 error which I will post to the end of this post
However to get it to work properly, you have to manually change the values of 
 label: 'my-agent2', <-
 walletConfig: {id: 'walletId2'}, <-
walletCredentials: {key: 'testkey0230482304823042304236'}, <-
 poolName: 'test-186', <-

and the mediator works!, stop the build re-build again and it fails, you have to go back and change this id values !!
It is just an overhead that we don't need, before it used to be the url of the mediator and things happen behind the hood

The log when it fails
[logann.txt](https://github.com/hyperledger/aries-framework-javascript/files/6840418/logann.txt)

**Comment by TimoGlastra** [comment]
I think you're running into the issue as described here: https://github.com/hyperledger/aries-framework-javascript/issues/381

Basically you need to provide the `mediatorConnectionsInvite` on first launch, and then remove it. I'd like to resolve this ASAP.

Could you confirm whether this is the issue you're running into?

**Comment by MosCD3** [comment]
Am not sure @TimoGlastra, it seems like that since it only happens after rebuilding the app
you can look at the log from the attached text file

**Comment by TimoGlastra** [comment]
Closing, we've fixed a lot of mediator issues. If the issue still persists please reopen the issue
