### ISSUE TITLE
Mediation for Edge Agents in Aries Framework JavaScript

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#40]
Current thoughts on implementing mediation for Edge Agents into Aries Framework JavaScript. I think in the beginning especially the Edge Agent role would be nice to implement, but eventually implementing the Mediator role would also be nice. This approach allows for interoperable mediaton with other agents that support the protocols mentioned in this document. Still some unresolved questions at the end. Would appreciate some other thoughts on this.

## Creating A Connection with the Mediator

The Mediator creates a [`Connection Invitation`](https://github.com/hyperledger/aries-rfcs/blob/master/features/0160-connection-protocol/README.md#0-invitation-to-connect) and sends it to the Edge Agent. If the Edge Agent wishes to connect to the Mediator it should respond with a [`Connection Request`](https://github.com/hyperledger/aries-rfcs/blob/master/features/0160-connection-protocol/README.md#1-connection-request). Because the Edge Agent has no endpoint to include in the `Connection Request`, an endpoint URI of `didcomm:transport/queue` will indicate to the Mediator that the Edge Agent does not have a direct endpoint and messages should be queued.

The `Connection Request` sent by the Edge Agent should include the [Transport Return Route Decorator](https://github.com/hyperledger/aries-rfcs/blob/master/features/0092-transport-return-route/README.md) to allow the Mediator to directly respond with a `Connection Response` message.

The Edge Agent and Mediator now have a connection. The Mediator will queue all messages it wants to send to the Edge Agent due to the `didcomm:transport/queue` endpoint.

## Requesting Mediation

The Mediator and Edge Agent now have a connection, but it is not clear yet whether the Mediator would like to mediate for the Edge Agent.

Using the [Mediator Coordination Protocol](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination) the Edge Agent can send a [`Mediation Request`](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination#mediation-request) to the Mediator. If the Mediator wishes to accept it will respond with a [`Mediation Grant`](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination#mediation-request) message. The `Mediation Grant` will include the `endpoint` and `routing_keys` properties. The Edge Agent should store these values as they will be used when creating new connections with other agents.

## Creating A Connection with Other Agents

Now that the Edge Agent made an agreement with the Mediator to act as an endpoint to receive messages, the Edge Agent can create connections with other agents using this endpoint.

It is not important whether the Edge Agent takes the role of **Inviter** or **Invitee** in the connection process. It is however important that before sending a message to the other agent the key used for this message is known by the Mediator. The Edge Agent should send a [`Keylist Update`](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination#keylist-update) message to the Mediator containing the key that will be used. The Mediator now knows that whenever a [`Forward`](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0094-cross-domain-messaging#corerouting10forward) message is received for this key, it is intended for the Edge Agent.

After the key is registered the connection flow can continue like normal. The Edge Agent can use the `endpoint` and `routing_keys` from the [Requesting Mediation](#requesting-mediation) step when exchanging DID Docs.

## Receiving Messages

As the Edge Agent has no endpoint the Mediator can't directly forward the messages to the Edge Agent when it receives them. The [Creating A Connection with the Mediator](#creating-a-connection-with-the-mediator) step allowed the Mediator to send a message to the Edge Agent using return routing. This is the implicit way for the Edge Agent to retrieve Messages. The explicit way is by using the [Pickup Protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0212-pickup/README.md)

### Implicit

Messages can be retrieved by the Edge Agent implicitly by connecting using the [Return Routing Protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0092-transport-return-route/README.md). It is recommended that a WebSocket transport be used between the Edge Agent and the Mediator for efficient message passing, and responsive message delivery when the Edge Agent app is open.

### Explicit

When WebSocket transport is not available and HTTP is used, return routing can only include one message in the HTTP response for each message the Edge Agent sends to the Mediator. This is where the [Pickup Protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0212-pickup/README.md#noop) can be used. Return routing will still be used, but by sending a [`Batch Pickup`](https://github.com/hyperledger/aries-rfcs/blob/master/features/0212-pickup/README.md#batch-pickup) message as Edge Agent the Mediator can respond with a single [`Batch`](https://github.com/hyperledger/aries-rfcs/blob/master/features/0212-pickup/README.md#batch) message containing multiple messages.

## References

- [Aries RFC 0211: Mediator Coordination Protocol](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination)
- [How Edge Agents can Gain an Endpoint](https://hackmd.io/sdrSodbFRJ2z3ezKLL4f7w)
- [Aries RFC 0092: Transports Return Route](https://github.com/hyperledger/aries-rfcs/blob/master/features/0092-transport-return-route/README.md)
- [Aries RFC 0212: Pickup Protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0212-pickup/README.md)
- [Aries RFC 0094: Cross-Domain Messaging](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0094-cross-domain-messaging)
- [Connections / DID Exchange / DID Document URI-less endpoints - hyperledger/aries-rfcs#405](https://github.com/hyperledger/aries-rfcs/issues/405)
- [Add Queue as a Transport option - decentralized-identity/didcomm-messaging#49](https://github.com/decentralized-identity/didcomm-messaging/pull/49)

## Questions

- I'm not sure whether it is required for the Edge Agent to send a message to the Mediator when opening a WebSocket connection with the Transport Return Routing decorator. I think this is necessary, because you can't just send an object with the `~transport` decorator without including a message `@type`. If this is the case we could maybe use [Noop](https://github.com/hyperledger/aries-rfcs/blob/master/features/0212-pickup/README.md#noop) message from the [Pickup Protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0212-pickup/README.md)
- As mentioned in the notes below, Aries Framework .NET supports an `add-device-info` message especially useful for push notifications. This is not possible with this approach. Is this desired?
- As also mentioned in the notes below, Aries Framework .NET uses a custom protocol, this means this approach won't be interoperable with Aries Framework .NET. Is this desired?

## Notes

- Aries Framework .NET created and implemented a custom [`basic-routing` protocol](https://github.com/hyperledger/aries-framework-dotnet/blob/d943af5e4de3f62289eb5ed105dc505e6ca3c8ab/src/Hyperledger.Aries.Routing/RoutingTypeNames.cs) that achieves approximately the same. Main differences are:
  - The protocol allows to create an inbox. Messages will be stored inside the inbox. To delete messages from the inbox a separate delete message type is used. With the pickup protocol messages are only kept until delivered.
  - The protocol has a message type to add device information. This is especially useful to send e.g. push notifications from the mediator to the edge agent when a message is received.
- Aries Framework Go implemented the approach described in this document. I think the only thing missing is the `didcomm:transport/queue` endpoint. The Route Coordination Protocol got renamed to Mediator Coordination Protocol and got some small updates. With some adjustments Aries Framework Go could be used as a Mediator for Aries Framework JavaScript Edge Agents

**Comment by jakubkoci** [comment]
Hi @TimoGlastra, thanks for the write-up, I went through it briefly and it was really helpful.  I'll look into it more over the weekend and we'll see how far I'll get :)

**Comment by jakubkoci** [comment]
I've prepared partial implementation here https://github.com/jakubkoci/aries-framework-javascript/tree/feature/connection-with-mediator.

It contains:
1. Creating A Connection with the Mediator
2. Receiving Messages - Explicit with pickup protocol

I'll create PR after merging #41  because I continued from that branch.

**Comment by TimoGlastra** [comment]
Great stuff!

I have some extra thoughts on this and other topics. Let's discuss during the call friday and keep this issue open to track progress.

**Comment by troyronda** [comment]
FYI: Updates were applied to aries-framework-go.

- https://github.com/hyperledger/aries-framework-go/pull/1827
- https://github.com/hyperledger/aries-framework-go/pull/1825

@TimoGlastra

**Comment by TimoGlastra** [comment]
Awesome. I think everything is in place then to use framework-go as a mediator for framework-javascript. 

 @troyronda Some questions on the go implementation:
- Is it correct the pickup protocol is not implemented?
- What does the edge agent send to the mediator when opening a websocket connection? As it needs the `~transport` decorator (see the first question in the original issue). 
- When I looked trough the code it seemed like forward messages are not stored at the moment if the mediator can't directly send them to the receiver edge agent. Is this correct?

**Comment by rolsonquadras** [comment]
@TimoGlastra 

> Awesome. I think everything is in place then to use framework-go as a mediator for framework-javascript.
> 
> @troyronda Some questions on the go implementation:
> 
> * Is it correct the pickup protocol is not implemented?

Yes, the protocol is not implemented yet

> * What does the edge agent send to the mediator when opening a websocket connection? As it needs the `~transport` decorator (see the first question in the original issue).

That's correct.Currently, only `all` [return route option](https://github.com/hyperledger/aries-rfcs/tree/master/features/0092-transport-return-route#tutorial) in `~transport` is [supported in aries-framework-go](https://github.com/hyperledger/aries-framework-go/blob/master/docs/didcomm_mediator.md#limitations).

> * When I looked trough the code it seemed like forward messages are not stored at the moment if the mediator can't directly send them to the receiver edge agent. Is this correct?

Yes. At the moment, the edge agent needs to be online(active socket connection to the router) when router receives message for that particular agent.

**Comment by jakubkoci** [comment]
Requesting Mediation part will be solved in #63
