### ISSUE TITLE
docs for every package

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/aries-framework-javascript#409]
Every package in this monorepo should contain a readme that elaborates a bit on how that package works. When you go to npm it would be nice to see something small to see how that package would work.

**Comment by TimoGlastra** [comment]
Agreed! However I think we can also get away with linking to the `/docs` directory. A small mention about what the package does would be good, but I think it will be easier to keep docs centralized

**Comment by blu3beri** [comment]
That sounds like a good solution.
