### ISSUE TITLE
Error: "url" could not be found

### ISSUE THREAD

**Issue by seajensen** [hyperledger/aries-framework-javascript#461]
I've been working to update AFJ in the Cardea-Mobile-Holder app. When I attempt to use "0.1.0-alpha.269" I encounter the following error:
<img width="1060" alt="Screen Shot 2021-09-20 at 12 18 29 PM" src="https://user-images.githubusercontent.com/42650494/134073726-012ed0f4-d730-4010-ae60-08ce4de9eab6.png">

When I remove the "url" line from node_modules, or update to "0.1.0-alpha.273" then I instead encounter this error:
<img width="784" alt="Screen Shot 2021-09-20 at 1 03 05 PM" src="https://user-images.githubusercontent.com/42650494/134073905-59bbec61-fa34-47e6-9c74-c3f551f9c6b2.png">

This isn't an error I encountered prior to updating. I'm not 100% sure AFJ is causing it, but it seems like newer versions of AFJ might not mesh well with Hermes.

**Comment by JamesKEbert** [comment]
@blu3beri any insight? Seems like it may have blown up with the url package changes in your recent PR, but it could be unrelated.

**Comment by TimoGlastra** [comment]
@blu3beri Could the problem be that hermes doesn't support TextDecoder (which may be used (indirectly) by query-string?)

**Comment by blu3beri** [comment]
> @blu3beri Could the problem be that hermes doesn't support TextDecoder (which may be used (indirectly) by query-string?)

I do think that that is the issue. However I checked all the dependencies of query-string and they don't seem to depend on anything or use `TextDecoder` themselves. So I am curious where it comes from.

We did not introduce any new dependencies or updates to afj core / rn ?

**Comment by JamesKEbert** [comment]
> @seajensen could you run it again on version 270

Unfortunately this hasn't fixed the issue--thanks for your help digging into it. 😄

**Comment by blu3beri** [comment]
> > @seajensen could you run it again on version 270
> 
> Unfortunately this hasn't fixed the issue--thanks for your help digging into it. 😄 

Ah that is too bad. I think I will just do the parsing like before. It should suffice.

**Comment by JamesKEbert** [comment]
Hmmm this might be an us problem? I just tried version 264, I'm not super sure what version of the code it corresponds to, but it's older than your URL changes, so this issue may be unrelated.

**Comment by JamesKEbert** [comment]
After some further investigation we finally identified that the metro bundler config didn't get the `inlineRequires` to be set to true as part of a RN upgrade, and we had a duplicate import that was also throwing in problems. 
Sorry for the false alarm, I appreciate the help looking into it.
