### ISSUE TITLE
Electron docs

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/aries-framework-javascript#464]
The electron setup docs seem quite out-of-date (pre-monorepo). Since it was a not-super-great supported platform, is this something we should update or just remove and bring it back when more research and testing has been done.

If we want to keep it up-to-date I will gladly update those docs.

**Comment by TimoGlastra** [comment]
What do you think? I'm fine with both. I think it would be koop to keep Electron in, as it forces us to make everything work in a browser environment except Indy. So if it's not a lot of work I'll say let's update it. If it is, it may be better to remove it for now
