### ISSUE TITLE
client side security 

### ISSUE THREAD

**Issue by SalimiHabib** [hyperledger/aries-framework-javascript#485]
As far as I realized one   key  is created by client side script  for initialize secure connection to other agent(s) 
so 
how can we secure that  key?
I know the facts and benefit  about DID and Self-sovereign identity , but is that key need any consideration on security perspective ?
or I am in the  wrong way ?

**Comment by TimoGlastra** [comment]
Hi @SalimiHabib,

Security is an important aspect to take into account when building SSI applications, and you should make sure you protect the keys and credentials of your applications. Currently we're using Indy as the wallet, which will automatically encrypt all data in your wallet at rest. You need a key to unlock your wallet, which you should also keep secure (e.g. in the mobile wallets we're building using this framework we use hardware backed biometric unlock. So we depend on the security of the iOS/Android platforms to unlock the wallet).

However if you're looking for more sophisticated like a HSM, that is not supported currently. Does this answer your question? Happy to answer any more questions that you have

**Comment by SalimiHabib** [comment]
As you mentioned  using  iOS/Android platforms is a clever way to solve the problem(HSM not so popular) but  , is there any suggested tools or technic for  using Aries by WASM or client side JavaScript (like blazer web assembly)?

**Comment by TimoGlastra** [comment]
Closing, please open another issue @SalimiHabib if you have other questions
