### ISSUE TITLE
Support *Connectionless* Proof Request!

### ISSUE THREAD

**Issue by MosCD3** [hyperledger/aries-framework-javascript#492]
I can't seem to find a way to scan a QR code to respond to a proof request from a verifier. Is that not supported yet?

**Comment by TimoGlastra** [comment]
Were you able to figure this out @MosCD3?

**Comment by MosCD3** [comment]
No @TimoGlastra It didn't work
The function "recieveMessage" probably expects a packed message

**Comment by MosCD3** [comment]
Since this topic has more intrest, I attach this walkthrough text details. If there is any missing step or misplaced step please correct me @TimoGlastra 
We could also discuss that in our weekly meetings. Initiating proof request by scanning QR code is one of the major steps there. Thanks al
[Walkthrough_presentproof.txt](https://github.com/hyperledger/aries-framework-javascript/files/7469197/Walkthrough_presentproof.txt)
l

**Comment by TimoGlastra** [comment]
Few notes on where it is going wrong I think:

- AFJ doesn’t support v2 of the present proof protocol yet.
- You need to encode the presentation request as the d_m, from your example it looked like you were encoding the whole presentation record
- You need to include the ~service decorator on the presentation request message, not the presentation exchange record

**Comment by TimoGlastra** [comment]
Closing, please open a new issue if you're still encountering issues
