### ISSUE TITLE
Connection not getting established between agents

### ISSUE THREAD

**Issue by Enthusiast-block** [hyperledger/aries-framework-javascript#514]
Hi @blu3beri,

This is a follow up issue after :- https://github.com/hyperledger/aries-framework-javascript/issues/508
Yes, i had assigned autoAcceptConnection as True in both the agents, still I wasn't able to establish connection.

Also, is AFJ in working mode, such that the 2 agents would be able to establish connections, Send credentials and verify them?

**Comment by blu3beri** [comment]
Hmm, could you send a minimal version of the project? That would help with debugging. 

And yes! AFJ agents can create connections, issue credentials and verify them.

**Comment by Enthusiast-block** [comment]
Sample application :- 

faber.ts :- 

import { HttpOutboundTransport, Agent, InitConfig, ConnectionInvitationMessage, ConnectionRecord } from '@aries-framework/core'

import { agentDependencies, HttpInboundTransport } from '@aries-framework/node'


import express = require("express");
const app : any = express();
app.use(express.json());

app.set("port", 3000);

let agent: Agent = null
let aliceConnection: {
  invitation: ConnectionInvitationMessage
  connectionRecord: ConnectionRecord
}
let aliceConnectionRecord: ConnectionRecord

async function initializeAgent(){

 
  const agentConfig: InitConfig = {
    label: 'Agent: Faber',
    walletConfig: {
      id: 'Wallet: Faber',
      key: 'Key: Faber',
    },
    publicDidSeed: '000000000000000000000000Trustee1',
    autoAcceptConnections: true,
    genesisPath: '/home/user/Documents/Learnings/aries-learning/Indy-sdk/indy-sdk/cli/docker_pool_transactions_genesis',
    poolName: 'local_pool'
  }

  agent = new Agent(agentConfig, agentDependencies)

  const httpOutboundTransport = new HttpOutboundTransport()
  agent.registerOutboundTransport(httpOutboundTransport)
  
  try {
      await agent.initialize()
      console.log('Initialized agent!')
    } catch (error) {
      console.log(error)
    }
    
}


async function createConnection(){
  aliceConnection = await agent.connections.createConnection({
    autoAcceptConnection: true,
    alias: 'inviter',
  })
  console.log("\n\n --- Invitation -- " + JSON.stringify(aliceConnection.invitation.toUrl({ domain: 'http://127.0.0.1:3000' })) + "--- \n\n" )
  console.log("\n\n ---- aliceConnection State ---- " + aliceConnection.connectionRecord.state + " ---- \n\n")
}


async function checkConnectionState() {
  let connectionRecord = await agent.connections.getById(aliceConnection.connectionRecord.id)
  console.log("\n\n ---- connectionRecord State ---- " + connectionRecord.state + " ---- \n\n")  
}



app.post('/create-connection', async function(request, response){
  await createConnection()
  response.send('Success')
})

app.post('/check-connection-state', async function(request, response){
  await checkConnectionState()
  response.send('Success')
})

app.post('/initialize-agent', async function(request, response){
  await initializeAgent();
  response.send('Success');
})

const server = app.listen(app.get("port"), () => {
  console.log(
    "App is running on http://localhost:%d in %s mode",
    app.get("port"),
    app.get("env")
  );
});


alice.ts :- 

import { HttpOutboundTransport, Agent, InitConfig, ConnectionInvitationMessage, ConnectionRecord, InboundTransport } from '@aries-framework/core'

import { agentDependencies } from '@aries-framework/node'

import express = require("express");
const app : any = express();
app.use(express.json());

app.set("port", 4000);

let agent: Agent = null
let faberConnection: {
  invitation: ConnectionInvitationMessage
  connectionRecord: ConnectionRecord
}
let faberConnectionRecord: ConnectionRecord

async function initializeAgent(){

 
  const agentConfig: InitConfig = {
    label: 'Agent: Alice',
    walletConfig: {
      id: 'Wallet: Alice',
      key: 'Key: Alice',
    },
    publicDidSeed: '000000000000000000000000Trustee2',
    autoAcceptConnections: true,
    genesisPath: '/home/user/Documents/Learnings/aries-learning/Indy-sdk/indy-sdk/cli/docker_pool_transactions_genesis',
    poolName: 'local_pool'
  }

  agent = new Agent(agentConfig, agentDependencies)

  const httpOutboundTransport = new HttpOutboundTransport()
  agent.registerOutboundTransport(httpOutboundTransport)
  
  try {
      await agent.initialize()
      console.log('Initialized agent!')
    } catch (error) {
      console.log(error)
    }
    
}

async function receiveInvitation(invitationUrl: string){
  faberConnectionRecord = await agent.connections.receiveInvitationFromUrl(invitationUrl, {
    autoAcceptConnection: true,
    alias: 'invitee',
  })
  console.log("\n\n --- State --- " + faberConnectionRecord.state)
}

async function checkConnectionState(){
  let connectionRecord = await agent.connections.getById(faberConnectionRecord.id)
  console.log("\n\n --- connectionRecord State --- " + connectionRecord.state)
}


app.post('/receive-invitation', async function(request, response) {
  let body = request.body
  await receiveInvitation(body["invitationUrl"]);
  response.send('Success')
})

app.post('/check-connection-state', async function(request, response){
  await checkConnectionState()
  response.send('Success')
})

app.post('/initialize-agent', async function(request, response){
  await initializeAgent();
  response.send('Success');
})

const server = app.listen(app.get("port"), () => {
  console.log(
    "App is running on http://localhost:%d in %s mode",
    app.get("port"),
    app.get("env")
  );
});

**Comment by TimoGlastra** [comment]
Hi @Enthusiast-block,

It seems like you're not using the `HttpInboundTransport` that you imported. To use it:

- add `http://localhost:xxx` to endpoints array
- call `agent.registerInboundTransport(new HttpInboundTransport({ port: xxx }))`

Where you replace xxx with the port that you want the agent to run on.

Make sure the alice and faber agent use different ports.

**Comment by Enthusiast-block** [comment]
Hi @TimoGlastra 

I followed the above steps,

but it is giving me an error on the registerInboundTransport call - Argument of type 'HttpInboundTransport' is not assignable to parameter of type 'InboundTransport'.

I have "strictFunctionTypes": false, in tsconfig.json, still It is giving me that issue.

**Comment by TimoGlastra** [comment]
I've never seen this error before. Can you share a minimal repository that showcases the error? That would make it a lot easier to help you debug the issue

**Comment by TimoGlastra** [comment]
Are your versions of `@aries-framework/core` and `@aries-framework/node` the same?

**Comment by Enthusiast-block** [comment]
Hi @TimoGlastra,

I did some debugging in this. 
When I install the packages using npm install, at that time as it installs from the remote repo, using those packages as import it doesn't throw an error.

But When I took the clone of AFJ in my local system and ran a yarn build there and then added and linked the core and node packages that were in my local to my sample demo project at that time it throws an error.

**Comment by Enthusiast-block** [comment]
> I've never seen this error before. Can you share a minimal repository that showcases the error? That would make it a lot easier to help you debug the issue

Give me some time. I will provide you with a link to the repo

**Comment by Enthusiast-block** [comment]
Hi @TimoGlastra , @blu3beri .

This is the link to the repo :- https://github.com/HarshMultani/aries-framework-javascript

Can you try it. the changes added to this link are only those that are required to do a yarn build.
If you build the core and node from here and try to use it in your project, it might give an error.

**Comment by Enthusiast-block** [comment]
Hi @TimoGlastra , @blu3beri ,

I did some more testing, and I think that the start function in HttpInboundTransport and InboundTransport are not compatible because of the parameter Agent, eventhough they both point to the same Agent class,
Don't know why this is happening.

**Comment by TimoGlastra** [comment]
@Enthusiast-block the example repo and scripts you provided are incomplete. Could you provide all repositories needed (also the project using the local build of AFJ) with a detailed guide of how to reproduce the error?

In general it helps to get your issue resolved if you make it as easy as possible for maintainers to reproduce your errors. 

One think I did run into was that I wasn't able to get AFJ to build without removing `@types/indy-sdk` from the root `package.json`

**Comment by Enthusiast-block** [comment]
Hi @TimoGlastra , @blu3beri 
We were doing an npm install instead of a yarn install.
After a yarn install everything works smoothly.
Thanks for continuous responses in this issue.
