### ISSUE TITLE
Error occurs while unpacking ack message

### ISSUE THREAD

**Issue by standlove** [hyperledger/aries-framework-javascript#529]
Hi, 

Is the ack message supported? Thanks. 

```
 ERROR  ERROR: error while unpacking message {
  "error": {},
  "packedMessage": {
    "error": "Unhandled exception: Couldn't locate a message handler for type https://didcomm.org/issue-credential/1.0/ack",
    "errorType": "AriesFrameworkException"
  },
  "errorMessage": "Error unpacking message"
}
```

**Comment by TimoGlastra** [comment]
Yes the ack message for the issue credential protocol is supported in AFJ. The error you're seeing here is actually a response from Aries Framework .NET that doesn't support the `https://didcomm.org` prefix yet.

You can enable the `useLegacyDidSovPrefix` on the agent config to use the `did:sov` prefix for messages instead

See https://github.com/hyperledger/aries-framework-dotnet/blob/main/src/Hyperledger.Aries/Agents/AgentBase.cs#L177-L179 for relevant code in aries-framework-dotnet
