### ISSUE TITLE
Is "share credential with connection" feature supported in the framework

### ISSUE THREAD

**Issue by standlove** [hyperledger/aries-framework-javascript#530]
Hi,

The Trinsic wallet app has a feature to share the credential with the connection. Is this supported in the framework? 

Thanks.

**Comment by TimoGlastra** [comment]
You can send a presentation proposal to another agent which is what I think the Trinsic app uses for the share credential with connection feature.

**Comment by TimoGlastra** [comment]
Closing, please open new issues if you have other questions
