### ISSUE TITLE
Adding a basic "Sample" app to the framework 

### ISSUE THREAD

**Issue by MosCD3** [hyperledger/aries-framework-javascript#546]
This is a very basic sample mobile app I developed in React Native 
https://github.com/MosCD3/ComX4

Its meant to be for developers with some debugging and stripped of any UI
Could be injected as source in the repo or could be referenced in the documentation
Good as start up shell for any developer

**Comment by TimoGlastra** [comment]
I'm not sure we should add this to this project as it adds a lot of boilerplate code. But if you want to link to your repository from the README, that would be a good addition of a reference application. What do you think @MosCD3?

Closing for now
