### ISSUE TITLE
Handle attachments in a generic way

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#548]
We should add something to handle attachments in a generic way (ACA-Py has it). Data could be base64 or json (or others but the first two are most important)

Currently we assume base64 everywhere and use the `data.base64`, but it could also be in json form.

```ts
// new
const data = request.data.get() // could be either json or base64, but it doesn't matter

// old
const base64 = request.data.base64 // could be null
const data = base64decode(base64)

const data = request.data.json
```

Should be updated in `packages/core/src/decorators/attachment/Attachment.ts`

_Originally posted by @TimoGlastra in https://github.com/hyperledger/aries-framework-javascript/pull/531#discussion_r744883442_

**Comment by jakubkoci** [comment]
That could be good, at least for base64 and json. However, if I look at Aries RFC 0017: Attachments it can also contain links. Should we call some HTTP request in that case or just return the link?

**Comment by TimoGlastra** [comment]
@morrieinmaas and @annelein will be working on this

**Comment by TimoGlastra** [comment]
Fixed
