### ISSUE TITLE
Runtime switching of ledgers

### ISSUE THREAD

**Issue by amanji** [hyperledger/aries-framework-javascript#567]
As a user, I'd like the ability to toggle ledgers on/off at runtime (i.e. after of Agent initialization). Currently ledgers must be enabled/configured when the Agent is initialized.

**Comment by swcurran** [comment]
Isn't this something we want to hide from a user?  It's pretty obscure stuff.  If we have a list of ledgers, we can use multi-ledger to access all of them.

I can see having a "Developer Mode" flag that could be used to add some developer ledgers to the list, but I don't think this is something we want to expose to "human" users.

Or maybe I'm not understanding the implication of this user story.

**Comment by blu3beri** [comment]
Do you have an example of an use case? I agree with @swcurran that multi-ledger, as it is implemented now, is probably the best for most, if not all, cases.

**Comment by amanji** [comment]
Are there any situations where a wallet would connect to an issuer/verifier that's on a completely novel network than what is configured in the wallet?

**Comment by swcurran** [comment]
Yes, it is conceivable that would happen.  But then you get into other questions -- like should the user connect to the other network?  Has anything been done to check if that ledger should be used?  Where is the genesis file for the ledger?

Until we get "did:indy", then we would only be in a situation that the ledger object was not found -- we still wouldn't know where it is.  The issuer would have to provide instructions on how to add the ledger.  Very ugly...

Once "did:indy" is there -- the identifier itself would name the ledger, so at least the wallet could have a chance at finding the genesis file, and providing a decent prompt to the user.

**Comment by amanji** [comment]
So long as there are no performance impact to configuring a few different well-known ledgers ahead of time this issue can be put on hold for now.

**Comment by TimoGlastra** [comment]
There is a significant performance impact with each added ledger as it needs to resolve the requested object from all configured ledgers. So you should definitely be mindful of which ledgers you support

**Comment by amanji** [comment]
I think this can be closed.
