### ISSUE TITLE
Connection state should be updated when connection is deleted

### ISSUE THREAD

**Issue by amanji** [hyperledger/aries-framework-javascript#568]
Currently a connection can be removed using the `deleteById` connection service method. Unlike other methods, this does not emit a state change event for the connection, and as a result, the context provider for the `useConnections` react-hook is not updated.

This becomes relevant in scenarios where a user want's to terminate/remove a connection but the connection list is not updated unless the app is restarted.

**Comment by TimoGlastra** [comment]
This is also the case for all other record types. Do you think a state changed event would work for this? I'm thinking what the state should be in the connection record, and whether it may be easier to add another event type.

Suggestions welcome

**Comment by amanji** [comment]
Would the state: `Removed` or `Deleted` work? I'm not sure what the correct convention should be.

**Comment by TimoGlastra** [comment]
Yeah I think that could work. 

We're using the redux-store package which handles the side-effect of the delete connection method, so haven't ran into it ourselves. 

https://github.com/hyperledger/aries-framework-javascript-ext/blob/053a3c79273d268ec32e9848d125fb5667647e89/packages/redux-store/src/slices/connections/connectionsSlice.ts#L116-L121

@JamesKEbert how are you handling this in your applications that are not using the redux-store package?

**Comment by amanji** [comment]
Should I go ahead and work on this then?

**Comment by TimoGlastra** [comment]
Yeah sure! 

Not sure how you want to go about it, but I think it would be good only adding the state to the event, not to the connection record itself.

Will you only be adding this for connection, or also the other record types? We have ~5 (maybe more) and for consistency it would be good to add it to all record types

**Comment by amanji** [comment]
This issue can now be closed.
