### ISSUE TITLE
Add support for RFC 0035: Problem Report

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#58]
It would be also nice to define some structure or rules for error handling answering questions: 
- When and where we want to throw/handle errors?
- Problem report adopted into other protocols
- initiating problem report as standalone protocol

**Comment by nbAmit** [comment]
@jakubkoci @TimoGlastra  I Would like to work on this

**Comment by TimoGlastra** [comment]
Awesome!

**Comment by jakubkoci** [comment]
Shouldn't we reopen this issue? I think we have still a few things we should address before closing.

**Comment by TimoGlastra** [comment]
I think it would be better to open specific issues for the outstanding tasks.

Are you mainly talking about the outstanding tasks from the PR or the tasks form the list in this issue?
