### ISSUE TITLE
No message class found for message type "https://didcomm.org/issue-credential/2.0/offer-credential"

### ISSUE THREAD

**Issue by ripulbd** [hyperledger/aries-framework-javascript#607]
Hi,

I am using the Aries React Native Mobile Agent. I am having this peculiar issue which I did not have previously. When I received a credential from an agent, the credential is not being shown
![Screenshot from 2022-01-26 16-55-44](https://user-images.githubusercontent.com/1178467/151207439-29c96260-c9c7-4b3d-abbf-3a3f700f7d4d.png)
. Instead I can see this error message in the console: "[AriesFrameworkError: No message class found for message type "https://didcomm.org/issue-credential/2.0/offer-credential"]"

What is the root reason for this particular error message?

Thank you very much.

Regards,
Ripul

**Comment by blu3beri** [comment]
Hi, 

We do not support issue credential V2 right now. There is a pr open to support  it with Indy credentials. So right now you can only use V1 of the protocol.

**Comment by ripulbd** [comment]
Thanks a lot for the explanation. With your suggestion, I have been able to resolve the issue.
