### ISSUE TITLE
Mediator coordination protocol mediator role

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#63]
Add mediator coordination protocol as mediator role.

**Resources:**
- flow: https://github.com/hyperledger/aries-framework-javascript/issues/40
- https://github.com/hyperledger/aries-rfcs/blob/master/features/0211-route-coordination/README.md
- Issue for recipient role: #203

**Comment by TimoGlastra** [comment]
Fixed!
