### ISSUE TITLE
Validate tails file hashes with revocation

### ISSUE THREAD

**Issue by JamesKEbert** [hyperledger/aries-framework-javascript#642]
When presenting proof of non revocation we need to fetch tails files and we want to validate the hash of downloaded tails files against the hash recorded in the revocation registry definition on the ledger to ensure the tails file hasn't been tampered with. 

As part of AFJ's current process for downloading the tails files the revocation registry definition hash is supplied as an argument, but we need to generate the hash of the downloaded file and compare the two.

ACA-Py implementation: https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/revocation/models/revocation_registry.py#L189

**Comment by TimoGlastra** [comment]
This has been added now
