### ISSUE TITLE
Adding the ability to rotate wallet key

### ISSUE THREAD

**Issue by MosCD3** [hyperledger/aries-framework-javascript#671]
Reference to the conversation here #652 
I am working on adding a function to AFJ that will allow rotating key as part of security module work on Bifold or any other implementation wallet

**Comment by MosCD3** [comment]
Created a PR to reflect new attribute in type definition 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59256

**Comment by TimoGlastra** [comment]
Fixed in #672
