### ISSUE TITLE
Generic Repository Events

### ISSUE THREAD

**Issue by Przytua** [hyperledger/aries-framework-javascript#723]
As proposed by @TimoGlastra in #716:

> [...] we could maybe solve this generically by adding events to the repository level. This way we can have `RecordDeletedEvent`, `RecordSavedEvent`, `RecordUpdatedEvent`, etc...

**Comment by TimoGlastra** [comment]
We discussed this in the WG today (starting at 29:30 if you want to listen: https://wiki.hyperledger.org/download/attachments/62250923/video1405750752.mp4?version=1&modificationDate=1651158507433&api=v2)

The general consensus is that general repository events are useful and we would like to see this added to the framework. 

Is this something you're willing to open a PR for this @Przytua? We can merge https://github.com/hyperledger/aries-framework-javascript/pull/716 for now, but it may be better to switch to the generic events to avoid breaking changes.

**Comment by TimoGlastra** [comment]
> Since these would be breaking changes with the state update events anyway, 

I think the state changed events can be handled separately at a later time, so if we directly add the generic repository events there won't be any breaking changes is it's just a new feature.

> I'd suggest to merge https://github.com/hyperledger/aries-framework-javascript/pull/716 for now,

Sure thats fine by me. But if your PR will be ready before we mark the 0.2.0 release I don't see a reason to keep them in TBH.

**Comment by Przytua** [comment]
Ah, ok. So yeah, let's leave #716 in PR, and if I won't make it before the release (which I hope won't happen), you can merge it, and generic ones would be added to next version.

By the way, is there any planned date for 0.2.0 release?
