### ISSUE TITLE
Add support for mediator role for pickup v2 protocol

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#727]
As part of PR #711 support for the recipient role was added. This issue tracks the progress of also adding support for the mediator role.

In addition when adding support for the mediator, we should also add e2e tests to test the whole flow of picking up messages, which can be complex when only supporting one side of the protocol.

RFC: https://github.com/hyperledger/aries-rfcs/tree/main/features/0685-pickup-v2

**Comment by genaris** [comment]
Is anyone working on this at the moment? Otherwise I can pick it up (yeah I know, nice pun :smile:)

**Comment by TimoGlastra** [comment]
> Is anyone working on this at the moment? Otherwise I can pick it up (yeah I know, nice pun :smile:)

I'm not aware of anyone working on this, so it's yours to take! 

If you're doing some refactoring, we also have this issue to untangle all of the routing protocols into separate services, maybe it helps to keep that in mind and make some first steps at it for the pickup v2 protocol: https://github.com/hyperledger/aries-framework-javascript/issues/800
