### ISSUE TITLE
Deleting a credential record should delete the associated didcomm messages

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#728]
When deleting a record from the service or module level it should delete all associated didcomm messages. 

We can do this by finding all `DidCommMessageRecord` where the `associatedRecordId` matches with the record that will be deleted.

TODO:
- [ ] Add a new config property `deleteAssociatedDidCommMessages` to `DeleteCredentialOptions`.
- [ ] In `CredentialService.delete` check if `deleteAssociatedDidCommMessage` is true (should be true by default), if so delete the assocaited didcomm messages by first retrieving them:
	- `didCommMessageRepository.findByQuery({ associatedRecordId: credentialRecord.id })`
	- delete all records returned from the query

**Comment by morrieinmaas** [comment]
@TimoGlastra can you assign me pls?
