### ISSUE TITLE
Complex storage queries (Wallet Query Language (WQL))

### ISSUE THREAD

**Issue by karimStekelenburg** [hyperledger/aries-framework-javascript#739]
For some use cases it's currently required to query the `StorageService` multiple times in a row. This would not be necesarry if the `StorageService` would expose an API that allows for complex queries that include `$and`, `$or` and `$not` clauses.

We should implement the Wallet Query Language (WQL) as specified by [Indy doc 011](https://github.com/hyperledger/indy-sdk/tree/master/docs/design/011-wallet-query-language).

**Comment by blu3beri** [comment]
Do you think we should just allow a WQL string or should we create a builder for this? Would be quite a nice feature to have, and with a builder we could also expose it publicly.
