### ISSUE TITLE
Fix inconsistencies in issue credential and present proof modules API

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#755]
With the enormous changes both the credential and proof modules have been through it is expected there are some inconsistencies in the public API between the modules. For now we should just focus on the inconsistencies in the public api, we can then focus on inconsistencies on lower levels in the future.

**Comment by genaris** [comment]
Can this be considered to be completed now that Proofs module has been refactored in 0.3.0-pre branch?

**Comment by TimoGlastra** [comment]
No not yet. It could however be separated into two issues:
1. Make the public api of both APIs consistent. This means adding missing methods (getFormatData, getRequestMessage, etc..)
2. Make the internal api of both modules consistent. The interfaces use different naming and could be unified more.


1. Should be fixed before the 0.3.0 release to make the proofs module really usable. 2. can be fixed later as it is only internal api changes
