### ISSUE TITLE
Add documentation on how to use postgres storage in Node.JS

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#758]
PR #699 adds support for using a postgres wallet type in Node.JS. It would be nice to add some documentation on how to install the postgres plugin on different platforms, and also on how to use it with AFJ.

@sairanjitAW is this something you're willing to take a look at?

**Comment by sairanjitAW** [comment]
@TimoGlastra Yes. I will add documentation for the same.

**Comment by TimoGlastra** [comment]
Awesome, thanks!

**Comment by sairanjitAW** [comment]
Yes, I was able to add for Linux and Mac but for windows, I was not able to prepare as of now. I will add the PR for that today itself.
