### ISSUE TITLE
Add `Logger` interface with default `ConsoleLogger` implementation

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#77]
Current logger can only log messages and json. However to allow framework users to gain insights in the activity of the framework at different levels of detail we should have multiple log levels.

I think something like:
- trace
- debug
- info
- warning
- error

Questions:
- Custom implementation vs logger library

[Winston](https://github.com/winstonjs/winston) seems like a good fit. It has a lot of customisability and is very mature.
We should at least abstract the logger away in a Logger class that doesn't expose the logging library used.

**Comment by icc-romeu** [comment]
@TimoGlastra winston is awesome but it depends on node so this could not be used -for example- by a React Native App without "hacking" a bit your App code. 

I would prefer to create an interface for the logger and a basic implementation for the logger, maybe using the basic "console.log". 

Hence, the logger could be optionally passed as a parameter to the agent constructor and in this way, you may use winston just implementing the interface.

This gives the user the power to stay with the basic implementation, or provide one that fits more its project.
