### ISSUE TITLE
Posgresql for framework development

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#771]
As a developer, I want to run all the tests with the least amount of external dependencies, so that I can contribute to a small part of the framework without bothering about the rest so much and not breaking it.

Current:
* There is a test `postgres.test.ts` requiring the installation of PostgreSQL database (if I understand it correctly).

Expected:
* We need to add a description of how to install Postgres dependencies to `DEVREADME.md` or we need to figure out how to get rid of it by splitting tests into some separate groups.

**Comment by TimoGlastra** [comment]
Related issue: https://github.com/hyperledger/aries-framework-javascript/issues/758
