### ISSUE TITLE
@type transform is missing for v2 credentials preview message

### ISSUE THREAD

**Issue by nbAmit** [hyperledger/aries-framework-javascript#774]
I was doing testing the V2 credential issuance with Aries cloud agent python and getting error `type must be equal to https://didcomm.org/issue-credential/2.0/credential-preview`
``
I think to resolved this we need to add below lines into the ../v2/V2CredentialPreview.ts

```
@Transform(({ value }) => replaceLegacyDidSovPrefix(value), {
    toClassOnly: true,
  })
```

**Comment by TimoGlastra** [comment]
I think this protocol was finalized after the transition to https://didcomm.org so it should never use the did:sov prefix. We can loosen it in AFJ, but would rather have other implementations follow the RFCs
