### ISSUE TITLE
[alpha.88+] Websocket connection to mediator not working

### ISSUE THREAD

**Issue by Iskander508** [hyperledger/aries-framework-javascript#807]
@KolbyRKunz, @TimoGlastra 

It seems this PR broke our setup: https://github.com/hyperledger/aries-framework-javascript/pull/787
We cannot create a connection with latest alpha versions in a react-native application, using websocket connection to an aca-py mediator.

I have digged a bit deeper and the problem seems to be on this line:
https://github.com/Indicio-tech/aries-framework-javascript/blob/f6d70b92ded4070d310e14c9775ad0a4ebef92ec/packages/core/src/modules/routing/RecipientModule.ts#L176
The `mediator` object doesn't have the `pickupStrategy` filled, so `mediator.pickupStrategy === undefined`.
Is it our mistake (passing wrong configuration somewhere) or a bug?

It is working fine with version alpha.87.

our agent config in the app:
```
const agentConfig: InitConfig = {
...
  mediatorConnectionsInvite: mediatorUrl,
  autoAcceptMediationRequests: true,
  mediatorPickupStrategy: MediatorPickupStrategy.Implicit,
};
```

**Comment by TimoGlastra** [comment]
Thanks for raising this issue @Iskander508. I've made a quick fix in this PR: https://github.com/hyperledger/aries-framework-javascript/pull/808

Will look soon to make the code a bit more robust and add test cases for these cases. The problem is that we assumed the mediation record would always store the pickup strategy, but in your case you're using the agent wide config parameter.

**Comment by Iskander508** [comment]
@TimoGlastra: I think I have found the issue in the code. You can check the https://github.com/hyperledger/aries-framework-javascript/pull/809

**Comment by KolbyRKunz** [comment]
Sorry for the confusion, I just have a follow up question about how this might affect things in the future. It might not even be possible but, if for some reason the mediator and the agent wide config parameter were somehow set to different strategies wouldn't we want to make sure those got synced and which one should we say is the source of truth in this instance? I am not sure if that is even possible or not but if one can be undefined while the other is defined it begs the question I think.
