### ISSUE TITLE
create test util for catching errors

### ISSUE THREAD

**Issue by morrieinmaas** [hyperledger/aries-framework-javascript#874]
see [this PR comment for more detail](https://github.com/hyperledger/aries-framework-javascript/pull/830#discussion_r893463474)

Happy to work on this.

**Comment by Iskander508** [comment]
How is this different from the jest `expect(...).toThrow(Error)`? E.g. used here: https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/core/src/modules/ledger/__tests__/IndyPoolService.test.ts#L86

**Comment by morrieinmaas** [comment]
@Iskander508 This is different in the way that it allows to catch the entire error object and do some more validation on this. The link above is just the example. With the `expect(...).toThrow(Error)` you are limited with the validation you can do in one go (eg validate error of type x is thrown or error message x is present). It's just a little bit of extra scrutiny

**Comment by TimoGlastra** [comment]
Doesn't seem so relevant anymore. We can add it when the need arises
