### ISSUE TITLE
AFJ holder agent submitting invalid proof to ACA-PY 0.7.4-rc1 version

### ISSUE THREAD

**Issue by sheraliinamdar** [hyperledger/aries-framework-javascript#901]
Hi Team, 
     We are using aca-py 0.7.4-rc1 and holder agent is AFJ 0.1.0 and whenever we are presenting the proof with valid credentials it is failing because of our holder agent is missing some time stamp while presenting the proof.  Here is the reference of issue https://github.com/hyperledger/aries-cloudagent-python/issues/1806. it would be great if you provide some pointers to resolve this issue And acapy 0.7.3 and below credentials are getting successful even if they are revoked.

**Comment by TimoGlastra** [comment]
See my comment in https://github.com/hyperledger/aries-cloudagent-python/issues/1806, this is fixed in 0.2.0 (soon to be released)
