### ISSUE TITLE
0.3.0 branch doesn't work in react native environment

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#905]
Hey folks! I've just tried to run this within a React Native environment--has that been recently tested? I've ran into a number of issues. The most problematic though is that the documentLoaderNode `require`'s `https`, which doesn't work in a RN context. I noticed [Karim's addition](https://github.com/hyperledger/aries-framework-javascript/pull/795/commits/c4fd640a8c8dcd0d3aa5d68cda88b19879a91664) that provided a conditional that would load the appropriate documentLoader, however the imports are already occurring so therefore the dependency still fails at bundle time. 

Is this likely to work on RN right now, or am I troubleshooting at a problematic point in development and it's on the list to fix RN support? 

I appreciate all the effort happening here :) Thanks!

_Originally posted by @JamesKEbert in https://github.com/hyperledger/aries-framework-javascript/issues/795#issuecomment-1165324881_

**Comment by JamesKEbert** [comment]
I'll note, if helpful, that in order to get the Mattr bbs-signatures library to be overridden according to the docs

> The resolution field says that any instance of `@mattrglobal/bbs-signatures` in any child dependency must be swapped
with `react-native-bbs-signatures`.
>#### npm
>
> 
> ```diff
> +   "overrides": {
> +     "@mattrglobal/bbs-signatures": "@animo-id/react-native-bbs-signatures@0.1.0",
> +   },
>     "dependencies": {
>       ...
> +     "@animo-id/react-native-bbs-signatures": "0.1.0",
>     }

I could not get the yarn docs to work. The npm override I _did_ get to work, however it created an alias/symlink, which React Native doesn't follow (https://github.com/facebook/metro/issues/1). So, in order to get it to work I had to in addition to the override add to my `extraNodeModules` in the metro.config.js (I've removed some of the other config stuff that's unrelated):
```
const extraNodeModules = {}
extraNodeModules["@mattrglobal/bbs-signatures"] = path.resolve(__dirname + '/node_modules/@animo-id/react-native-bbs-signatures'),

module.exports = (async () => {
  const metroConfig = {
    resolver: {
      extraNodeModules: extraNodeModules,
      sourceExts: [...sourceExts, 'cjs'],
    }
  };
  return metroConfig
})()
```

**Comment by TimoGlastra** [comment]
Related issue: https://github.com/hyperledger/aries-framework-javascript/issues/917

**Comment by TimoGlastra** [comment]
Also need to add resolutions/overrides for all digital credentials libraries (such as https://github.com/digitalcredentials/jsonld-signatures)
