### ISSUE TITLE
@aries-framework/core"' has no exported member named 'HttpInboundTransport'

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-framework-javascript#912]
I get the following error:

```
@aries-framework/core"' has no exported member named 'HttpInboundTransport'. Did you mean 'HttpOutboundTransport'?ts(2724)
HttpOutboundTransport.d.ts(4, 22): 'HttpOutboundTransport' is declared here.
```

When I try to setup the agent in NodeJS using Typescript:

```
import type { InitConfig } from '@aries-framework/core'
import { Agent } from '@aries-framework/core'
import { agentDependencies } from '@aries-framework/node'
import { HttpOutboundTransport, WsOutboundTransport, HttpInboundTransport } from '@aries-framework/core'

// The agent initialization configuration
const config: InitConfig = {
  label: 'docs-nodejs-agent',
  walletConfig: {
    id: 'wallet-id',
    key: 'testkey0000000000000000000000000',
  },
}

// Creating an agent instance
const agent = new Agent(config, agentDependencies)

// Registering the required in- and outbound transports
agent.registerOutboundTransport(new HttpOutboundTransport())
agent.registerInboundTransport(new HttpInboundTransport({ port: 3000 }))

// Function to initialize the agent
const initialize = async () => await agent.initialize().catch(console.error)
```

**Comment by TimoGlastra** [comment]
Ah this is a mistake in the docs. `HttpInboundTransport` should be imported from `@aries-framework/node`...

So:

```ts
import { HttpInboundTransport } from '@aries-framework/node'
```

@blu3beri could you fix this in the documentation (we should probably also extract the setup to snippets): https://aries.js.org/guides/getting-started/set-up

**Comment by dnaicker** [comment]
Thank you soo much for the help!

> Ah this is a mistake in the docs. `HttpInboundTransport` should be imported from `@aries-framework/node`...
> 
> So:
> 
> ```ts
> import { HttpInboundTransport } from '@aries-framework/node'
> ```
> 
> @blu3beri could you fix this in the documentation (we should probably also extract the setup to snippets): https://aries.js.org/guides/getting-started/set-up
