### ISSUE TITLE
indy-sdk-react-native maven and compileSdkVersion 

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-framework-javascript#916]
When trying to run the React Native Android setup using the install guide:

- `indy-sdk-react-native` is required after `importing aries` and adding agent to `App.js`, this hasn't been mentioned in the setup docs yet.  
- When doing an android run command, it displays two errors related to `indy-sdk-react-native` not being able to compile:

1. `Plugin with id 'maven' not found.`
2. `compileSdkVersion is not specified in build.gradle`

- I have logged an issue on `indy-sdk-react-native` github project https://github.com/hyperledger/indy-sdk-react-native/issues/48. It may be gradle 7 related migration issues. I tried to resolve manually.

- I just wanted to show there is a dependency on setting up which is not in the setup guide yet that might hinder first time users from running the setup guide

**Comment by TimoGlastra** [comment]
Thanks for raising this issue @dnaicker! I've responded to your issue in the indy-sdk-react-native repo

**Comment by TimoGlastra** [comment]
>  indy-sdk-react-native is required after importing aries and adding agent to App.js, this hasn't been mentioned in the setup docs yet.

What do you mean exactly with this?

**Comment by dnaicker** [comment]
> > indy-sdk-react-native is required after importing aries and adding agent to App.js, this hasn't been mentioned in the setup docs yet.
> 
> What do you mean exactly with this?

When running `npx react-native run-android` the application builds successfully although upon loading of the app in android the following error displays: `"Unable to resolve module indy-sdk-react-native" from react-native\build\index.js`





![Screenshot_20220630-170744_ReactNativeTest5](https://user-images.githubusercontent.com/7840952/176713045-3d714e4c-984b-4dd1-b1b7-f7a015fde71c.jpg)

**Comment by TimoGlastra** [comment]
Thanks for bringing that up, I've opened an issue in the docs repo and will add it asap: https://github.com/hyperledger/aries-javascript-docs/issues/47
