### ISSUE TITLE
CI is broken in 0.3.0-pre branch

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#923]
Opening a dedicated issue to track progress on fixing CI in 0.3.0-pre. It's failing consistently.

**Comment by blu3beri** [comment]
I will take a look at this today. 

It seems that the node-bbs-signatures fails on Linux + node 17/18 and possibly more node versions.

**Comment by TimoGlastra** [comment]
Do you know if these node versions are supported? If node 17/18 are not supported there's nothing we can do about it 🤷. We should just be clear to document it in that case and skip tests for bbs in node 17/18

**Comment by karimStekelenburg** [comment]
Adding the test results I previously posted in #935 here for context:

### Ubuntu
#### Specs
![CleanShot 2022-07-08 at 03 06 55](https://user-images.githubusercontent.com/18397186/177896428-f31cc549-80ce-484d-839d-f9f825c0881b.png)

#### Results for Node v14.19.3
![CleanShot 2022-07-08 at 02 52 42](https://user-images.githubusercontent.com/18397186/177896526-0a858c49-a5af-432f-b22a-b962a8639a34.png)

#### Results for Node v16.16.0
![CleanShot 2022-07-08 at 02 55 12](https://user-images.githubusercontent.com/18397186/177896604-76b5f86b-fbf1-401e-8b74-ea7be9631aad.png)

#### Results for Node v17.9.1
![CleanShot 2022-07-08 at 02 57 11](https://user-images.githubusercontent.com/18397186/177896680-d26e79be-9bc0-4533-a7c9-1576d8e59789.png)

#### Results for Node v18.5.0
![CleanShot 2022-07-08 at 03 12 44](https://user-images.githubusercontent.com/18397186/177896748-6abb69f3-9c8b-4bd8-a6a9-7d4d76c23efe.png)

### macOs (M1)
#### Specs
![CleanShot 2022-07-08 at 03 14 21](https://user-images.githubusercontent.com/18397186/177897043-985e01dc-c968-4a5d-9c83-affadca9c613.png)

#### Results for Node v14.20.0
![CleanShot 2022-07-08 at 03 16 40](https://user-images.githubusercontent.com/18397186/177897108-08024949-e93b-4a3d-bf3f-cf8ed94c68c3.png)

#### Results for Node v16.16.0
![CleanShot 2022-07-08 at 03 18 27](https://user-images.githubusercontent.com/18397186/177897272-7c8f0fe5-28c8-4325-9bf8-a097904d82f8.png)

#### Results for Node v17.9.1
![CleanShot 2022-07-08 at 03 20 11](https://user-images.githubusercontent.com/18397186/177897441-b99bb175-2cb7-4a64-94a8-dd046a3d3aba.png)

#### Results for Node v18.5.0
![CleanShot 2022-07-08 at 03 21 54](https://user-images.githubusercontent.com/18397186/177897686-f75cd5c8-74e4-47f8-a9e1-873901f4aa03.png)

**Comment by genaris** [comment]
So is there any clue about what the problem could be in CI with node 17/18? For development I'm using a x86_64 machine running Arch-based Linux (kernel 5.15.60) and all vc tests are passing. Also I've created a Dockerfile to replicate AFJ's CI setup (i.e. based in ubuntu-20.04 image and installing all dependencies) and it works fine as well.
