### ISSUE TITLE
Add deleteById method to storage service that doesn't require the record

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#925]
Currently when deleting a record you need to pass the record to the repository / storage service to delete the record. This is not a limitation from the indy-sdk and means you sometimes have to fetch the record just to delete it.

**Comment by tipusingh** [comment]
I want to work on this issue please, assign me on this.

**Comment by TimoGlastra** [comment]
Awesome! It's yours :)

Let me know if you have any questions
