### ISSUE TITLE
Query: is there a way to generate libindystrgpostgres.dll?

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-framework-javascript#928]
- I generated `libindystrgpostgres.so` file for postgres in WSL2, can it be used anywhere in Windows to integrate into Android React Native build or somewhere else?

- Is there a way to generate `libindystrgpostgres.dll`?
 
- How would one go about interacting and using `libindystrgpostgres.so/dll` for development?

**Comment by TimoGlastra** [comment]
Hi @dnaicker, I'm not familiar with using the postgres plugin on windows. 

Have you seen the documentation (it misses Windows setup, but may help): https://aries.js.org/guides/tutorials/postgres-database-nodejs

Do you want to connect from the wallet to the postgress database directly? I've never seen that pattern before, curious what your use case here. I think a more common approach is to create a web service that has access to the database and integrate the wallet with that web service

**Comment by blu3beri** [comment]
I don't quite understand what you mean. You cannot use the indypostgres storage right now in a React Native environment as the bindings are only created for Node.js.

If you want to use the plugin for Windows, you could create the `.dll` yourself:

```console
git clone https://github.com/hyperledger/indy-sdk
cd indy-sdk/experimental/plugins/postgres_storage
cargo build --release
cd target/release
# there should be a `libindystrgpostgres.dll`

# to get the full path:
echo $(pwd)/libindystrgpostgres.dll
```

Starting the node process with the plugin:

```console
LIB_INDY_STRG_POSTGRES=<THE_OUTPUT_FROM_ABOVE> yarn start
```

Hopefully it answers your question or points you in the right direction.

**Comment by dnaicker** [comment]
Thank you @blu3beri yes this helps a lot. 

Thank you @TimoGlastra the instructions on https://aries.js.org/guides/tutorials/postgres-database-nodejs help a lot as well on how to utilise the plugin.

**Comment by dnaicker** [comment]
@blu3beri When I try to build the `libindystrgpostgres.dll` on windows, I get the following error: 

> error[E0463]: can't find crate for `vcpkg`
>  --> C:\Users\denai\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-libindy-wrapper-0.2.13\build.rs:3:1
>   |
> 3 | extern crate vcpkg;
>   | ^^^^^^^^^^^^^^^^^^^ can't find crate

**Comment by TimoGlastra** [comment]
@sairanjitAW were you able to build the Postgres plugin for windows?

**Comment by sairanjitAW** [comment]
@TimoGlastra Yes I was able to build it.

**Comment by sairanjitAW** [comment]
@dnaicker I have added a PR for the docs for Postgres plugin for windows 
https://github.com/hyperledger/aries-javascript-docs/pull/50
if everything works fine according to the docs we can then merge the PR

**Comment by TimoGlastra** [comment]
@dnaicker I've merged the docs PR from @sairanjitAW with instruction on how to build the postgres plugin for windows. Please open a new issue if you're still encountering issues

https://aries.js.org/guides/tutorials/postgres-database-nodejs/windows
