### ISSUE TITLE
Query: is there a list of all available functions that one can call for connection, issuer or verifier to expand upon the sample docs tutorial?

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-framework-javascript#939]
I wanted to find out if there is a list of functions, documentation-directory wise, that are available to expand upon the functionality presented in the online tutorial documentation?

For instance if an invitation is already received, how would one check existing invitations against account holder, is there perhaps a function one could call to acquire that information?

**Comment by TimoGlastra** [comment]
Hi @dnaicker, I'm not sure if I fully understand your request. I've created a template in the docs repo, could you open an issue there?

https://github.com/hyperledger/aries-javascript-docs/issues/new?assignees=&labels=request&template=documentation-request.yml&title=%5BRequest%5D%3A+

**Comment by dnaicker** [comment]
Thank you Timo
