### ISSUE TITLE
Make sure base64 encoding works on other platforms

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#95]
Module `SignatureDecoratorUtils` is using [base64url](https://www.npmjs.com/package/base64url) package which apparently doesn't work on React Native. There is an issue about that in package repo https://github.com/brianloveswords/base64url/issues/50.

I looked into the code and the problem is probably dependency on `Buffer` which is a globally available object in Node.js. I see two solutions:
1. Implement functionality on our own.
2. Use a different npm package with support for the web and React Native platform.

In both cases, I would suggest introducing a class `JsonEncoder` which would hide implementation details and provide the same API across the framework independently on a particular package.

**Comment by TimoGlastra** [comment]
This is fixed by #135
