### ISSUE TITLE
git clone issue with packages/core/src/modules/dids/methods/peer/__tests__/DidPeer.test.ts

### ISSUE THREAD

**Issue by dineshnextbrain** [hyperledger/aries-framework-javascript#984]
![image](https://user-images.githubusercontent.com/111457365/185216093-9fdc84bf-5cc3-4992-9c7a-e9f163af673b.png)

**Comment by blu3beri** [comment]
@TimoGlastra did you not fix this?

**Comment by genaris** [comment]
It seems that there were two cache files added in #717 while #963 only removed one.

**Comment by genaris** [comment]
BTW @dineshnextbrain what's the environment (OS, Git client version, etc.) where this issue can be reproduced? I've tested current repo status under Windows 10 21H1 and Git 2.11.1.windows.1 and checks out main branch properly.
