### ISSUE TITLE
Unable to resolved https module in react-native 

### ISSUE THREAD

**Issue by nbAmit** [hyperledger/aries-framework-javascript#993]
Unable to resolved `https` module from `/node_modules/@digitalcredentials/js onld/lib/documentLoaders/node.js `

I am trying to use PPV2 in react-native from branch `0.3.0-pre`, Once I installed the packages and trying to run the app I am getting below error.

<img width="1356" alt="Screenshot 2022-08-18 at 3 31 52 PM (1)" src="https://user-images.githubusercontent.com/91456036/186880157-5a0676c5-0f02-42c4-890a-f05c7ef12528.png">

**Comment by TimoGlastra** [comment]
Can you add some context on what you're trying to do, which environment you're in, maybe a code example, etc..???
